import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 11,
  slug: "update-hooks-deploy",
  title: "hook_update_N & hook_post_update in Deployments",
  part: "Deployment Mechanics",
  estMinutes: 13,
  summary:
    "Config import moves YAML into the active store and nothing else — tables, data fixes and content transforms belong in update hooks, whose slot in the deploy sequence decides whether they see the old config or the new.",

  concept: `
## What \`drush cim\` will never do for you

Configuration import writes config objects. It does not create a database
table, it does not backfill a column, it does not re-save 40,000 nodes so a
new computed field populates, and it does not delete orphaned rows left by a
module you removed. Those are *data* operations, and Drupal has exactly one
mechanism for them: update functions, discovered by function name and run
once per site.

That "found by name" detail matters. Update functions are not dispatched
through the hook system at all — the module handler never sees them — which
is why the object-oriented \`#[Hook]\` attribute style does not cover them.
They stay procedural, in \`MODULE.install\` and \`MODULE.post_update.php\`.

### Three slots, not one

- **\`MODULE_update_N()\`** in \`MODULE.install\`. Numbered; Drupal compares \`N\`
  against the module's installed schema version (stored in the \`key_value\`
  table, collection \`system.schema\`) and runs everything higher, in numeric
  order. Core numbers these \`<major><minor><counter>\` — \`system_update_10201\`.
  These run **early**, before the container is guaranteed to reflect the new
  code. Schema changes and raw SQL only.
- **\`MODULE_post_update_NAME()\`** in \`MODULE.post_update.php\`. Not numbered —
  tracked by function name in the \`post_update\` key-value collection, so it
  runs once and is never renumbered. Runs after **all** \`hook_update_N\` across
  every module, with a fully rebuilt container. Entity API, config API,
  services: all fair game.
- **\`MODULE_deploy_NAME()\`** in \`MODULE.deploy.php\`. A Drush construct, not
  core, executed by \`drush deploy:hook\`.

### The order, and the trap inside it

\`drush deploy\` (Drush 13 and later, the versions you use with Drupal 10.3+/11)
runs a fixed sequence:

\`\`\`
drush updatedb
drush config:import
drush cache:rebuild
drush deploy:hook
drush cache:warm       # only on Drupal 11.2+
\`\`\`

Drush 12 and earlier ran a different shape — \`updatedb --no-cache-clear\`,
plus a \`cache:rebuild\` *before* the import as well as after — so older
runbooks and blog posts will not match what your Drush actually does. The
part that has never changed is the part that matters below.

\`updatedb\` runs **before** \`config:import\` because an update hook may create
the schema that incoming config depends on — a new field storage in
\`field.storage.node.audit_ref\` is useless if the table it targets does not
exist yet. But note what that ordering costs you: **\`hook_post_update_NAME\`
runs before your new config is imported.** A post-update that expects the
workflow, view mode or field config you just exported will fail on a clean
production run and pass on your laptop, where the config is already active.
That gap is exactly why Drush added \`hook_deploy_NAME\` — same capabilities,
but on the far side of \`config:import\`.

### Idempotency and class drift

Two rules that cause most real incidents:

1. **Assume it may run twice.** A half-finished batch, a timeout, a restored
   snapshot — write \`if (!$schema->fieldExists(...))\` and guard your inserts.
2. **Do not call your own module's classes.** The update runs against whatever
   version of \`MyService\` exists eighteen months from now. Inline the logic,
   or use \`\\Drupal::database()\` and the config API directly. A constant you
   later rename turns a two-year-old update into a fatal on someone's
   first deploy.

Long updates take a \`&$sandbox\` and set \`$sandbox['#finished']\` between 0 and
1 so the batch runner re-enters them.

### Testing

The only honest test is \`drush sql:drop && drush sql:cli < prod.sql\` on a
scratch environment, then \`drush deploy\`. Update hooks touch data volumes and
edge-case rows your dev database has never seen.
`,

  comparisons: [
    {
      label: "The migration slot",
      intro:
        "Both frameworks version the database separately from the code and record what has run. The bookkeeping differs: Doctrine tracks class names, Drupal tracks an integer per module.",
      leftLang: "php",
      rightLang: "php",
      php: `<?php
// migrations/Version20260811093000.php — generated by
// bin/console doctrine:migrations:diff
namespace DoctrineMigrations;

use Doctrine\\DBAL\\Schema\\Schema;
use Doctrine\\Migrations\\AbstractMigration;

final class Version20260811093000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add intranet_audit table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE intranet_audit (
            id INT AUTO_INCREMENT NOT NULL,
            uid INT NOT NULL,
            created INT NOT NULL,
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE intranet_audit');
    }
}

// Applied rows are recorded in doctrine_migration_versions.
// Deploy step: bin/console doctrine:migrations:migrate --no-interaction`,
      ts: `<?php
// modules/custom/intranet_core/intranet_core.install

/**
 * Create the {intranet_audit} table.
 */
function intranet_core_update_10003(): void {
  $schema = \\Drupal::database()->schema();

  // Idempotent: a retried deploy must not explode here.
  if ($schema->tableExists('intranet_audit')) {
    return;
  }

  $schema->createTable('intranet_audit', [
    'description' => 'Audit trail for intranet actions.',
    'fields' => [
      'id'      => ['type' => 'serial', 'not null' => TRUE],
      'uid'     => ['type' => 'int', 'not null' => TRUE, 'default' => 0],
      'created' => ['type' => 'int', 'not null' => TRUE, 'default' => 0],
    ],
    'primary key' => ['id'],
    'indexes' => ['uid_created' => ['uid', 'created']],
  ]);
}

// Drupal stores 10003 in key_value / collection "system.schema".
// There is no down(). Rolling back means restoring the database.`,
      note: "Doctrine has down(); Drupal has no rollback whatsoever. Your rollback plan is the pre-deploy database snapshot, and every deploy runbook must say so explicitly.",
    },
    {
      label: "The deploy script",
      intro:
        "The four-person team wants one command that CI and a human both run. Compare a typical Symfony deploy step with Drupal's, and note where the config import sits.",
      leftLang: "bash",
      rightLang: "bash",
      php: `#!/usr/bin/env bash
set -euo pipefail

# Symfony: code first, then schema, then warm caches.
composer install --no-dev --optimize-autoloader --no-interaction

# config/packages/*.yaml is already in the artefact — no import step,
# the container compiles it. Secrets come from env vars / vault.
bin/console cache:clear --env=prod
bin/console cache:warmup --env=prod

# The single stateful step.
bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

# Anything migrations cannot express is a bespoke console command
# that someone has to remember to run.
bin/console app:backfill-audit-uuids --no-interaction

bin/console assets:install --symlink public`,
      ts: `#!/usr/bin/env bash
set -euo pipefail

# 1. New code on disk.
composer install --no-dev --optimize-autoloader --no-interaction

# 2. Safety net. There is no "undo" for updatedb or cim.
drush sql:dump --gzip --result-file=/backups/pre-deploy-$(date +%s).sql

# 3. Everything below is what "drush deploy" does on Drush 13 and later. Spelled
#    out so you can see the ordering; in CI just run: drush deploy -y
drush updatedb -y                    # hook_update_N, then hook_post_update_NAME
drush config:import -y               # sync/ -> active storage
drush cache:rebuild
drush deploy:hook -y                 # hook_deploy_NAME, post-import
drush cache:warm                     # only on Drupal 11.2+

# 4. Prove it landed.
drush config:status                  # must report no differences
drush status --field=bootstrap`,
      note: "Symfony has no config:import step at all — environment config is compiled into the container from the artefact. Drupal's active config lives in the database, so importing it is a mutating deploy step that can fail halfway.",
    },
    {
      label: "Post-update vs deploy hook",
      intro:
        "A new editorial workflow ships as config, and existing nodes must be moved onto it. Put that logic in the wrong slot and it works locally but dies in production.",
      leftLang: "php",
      rightLang: "php",
      php: `<?php
// src/Command/AssignWorkflowCommand.php
// Symfony: ordering is whatever your deploy script says. You control it
// by putting the line after the config is on disk — which it always is,
// because config ships in the artefact, not in the database.
#[AsCommand(name: 'app:assign-workflow')]
final class AssignWorkflowCommand extends Command
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly WorkflowRegistry $workflows,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $i, OutputInterface $o): int
    {
        // Safe: the workflow definition was loaded at container compile
        // time, long before this command ran.
        $workflow = $this->workflows->get('editorial');
        // ... assign, flush ...
        return Command::SUCCESS;
    }
}`,
      ts: `<?php
// intranet_core.post_update.php
// WRONG SLOT: runs inside "drush updatedb", i.e. BEFORE config:import.
// workflows.workflow.editorial does not exist yet on production.
function intranet_core_post_update_assign_workflow(): void {
  $workflow = \\Drupal::entityTypeManager()
    ->getStorage('workflow')
    ->load('editorial');
  $workflow->getTypePlugin();  // fatal: load() returned NULL on prod
}

// intranet_core.deploy.php
// RIGHT SLOT: "drush deploy:hook" runs after config:import.
function intranet_core_deploy_assign_workflow(array &$sandbox): string {
  $storage = \\Drupal::entityTypeManager()->getStorage('node');

  if (!isset($sandbox['ids'])) {
    $sandbox['ids'] = $storage->getQuery()
      ->accessCheck(FALSE)
      ->condition('type', 'policy')
      ->execute();
    $sandbox['total'] = count($sandbox['ids']);
    $sandbox['done'] = 0;
  }

  foreach (array_splice($sandbox['ids'], 0, 50) as $nid) {
    $storage->load($nid)?->set('moderation_state', 'draft')->save();
    $sandbox['done']++;
  }

  $sandbox['#finished'] = $sandbox['total'] ? $sandbox['done'] / $sandbox['total'] : 1;
  return sprintf('Moved %d of %d policy nodes.', $sandbox['done'], $sandbox['total']);
}`,
      note: "The failure only appears on an environment where the config is genuinely new. Your laptop already has the workflow active, so the post_update version passes locally and fatals on stage — the classic 'works on my machine' deploy bug.",
    },
    {
      label: "Surviving your own refactors",
      intro:
        "An update hook written today runs on a site that has not deployed for a year, against code from that year's HEAD. Both ecosystems warn about it; only one has a compiler to help you.",
      leftLang: "php",
      rightLang: "php",
      php: `<?php
// Doctrine's own docs: migrations must not use entities or repositories.
// This is the version people write and regret.
public function up(Schema $schema): void
{
    // BAD: AuditLog::STATUS_PENDING may be renamed or deleted, and
    // the entity mapping will not match the schema at this point in
    // history. A year later this migration fatals.
    $this->connection->executeStatement(
        'UPDATE intranet_audit SET status = :s WHERE status IS NULL',
        ['s' => AuditLog::STATUS_PENDING],
    );
}

// GOOD: freeze the value. Raw SQL only, no application classes.
public function up(Schema $schema): void
{
    $this->addSql("UPDATE intranet_audit SET status = 'pending'
                   WHERE status IS NULL");
}`,
      ts: `<?php
// BAD: couples a permanent, once-only function to today's code.
function intranet_core_update_10004(): void {
  // AuditService may be renamed, get new constructor args, or vanish.
  \\Drupal::service('intranet_core.audit')->backfillUuids();
}

// GOOD: self-contained, idempotent, batched, no module classes.
function intranet_core_update_10005(array &$sandbox): string {
  $db = \\Drupal::database();

  if (!isset($sandbox['max'])) {
    $sandbox['max'] = (int) $db->query(
      'SELECT COUNT(*) FROM {intranet_audit} WHERE uuid IS NULL'
    )->fetchField();
    $sandbox['progress'] = 0;
  }

  if ($sandbox['max'] === 0) {
    $sandbox['#finished'] = 1;
    return 'Nothing to backfill.';
  }

  $ids = $db->select('intranet_audit', 'a')
    ->fields('a', ['id'])
    ->isNull('a.uuid')
    ->range(0, 200)
    ->execute()
    ->fetchCol();

  foreach ($ids as $id) {
    // Frozen literal service id, not a class constant that may move.
    $db->update('intranet_audit')
      ->fields(['uuid' => \\Drupal::service('uuid')->generate()])
      ->condition('id', $id)
      ->execute();
    $sandbox['progress']++;
  }

  $sandbox['#finished'] = $sandbox['progress'] / $sandbox['max'];
  return sprintf('Backfilled %d of %d rows.', $sandbox['progress'], $sandbox['max']);
}`,
      note: "Both ecosystems say the same thing: an update is a historical record, not application code. Core's uuid service is a safe exception because it is guaranteed stable — your own service ids are not.",
    },
  ],

  playground: {
    intro:
      "A pure-PHP model of the bookkeeping Drush does before it touches anything: read the installed schema versions and the already-run update names, diff them against what the codebase ships, and print the plan in drush deploy order. Watch which bucket each function lands in relative to config:import.",
    lang: "php",
    code: `<?php

// What the production database already knows.
// Schema versions live in the key_value table, collection "system.schema".
// Finished post-updates live in the "post_update" collection, by function name.
$installedSchema = ['intranet_core' => 10002, 'intranet_search' => 10001];
$ranPostUpdates  = ['intranet_core_post_update_rebuild_search_index'];
$ranDeployHooks  = [];

// What the freshly deployed codebase ships.
$codebase = [
  'intranet_core' => [
    'update' => [
      10002 => 'Create the {intranet_audit} table.',
      10003 => 'Add the uuid column to {intranet_audit}.',
      10004 => 'Backfill uuid values in {intranet_audit}.',
    ],
    'post_update' => [
      'rebuild_search_index' => 'Rebuild the search index.',
      'resave_landing_pages' => 'Re-save landing pages so the new field populates.',
    ],
    'deploy' => [
      'assign_workflow' => 'Assign the editorial workflow that config:import just created.',
    ],
  ],
  'intranet_search' => [
    'update'      => [10001 => 'Widen {search_log}.query to 512 characters.'],
    'post_update' => [],
    'deploy'      => [],
  ],
];

$updates = [];
$postUpdates = [];
$deployHooks = [];

foreach ($codebase as $module => $defs) {
  // hook_update_N: pending when N is greater than the installed schema version.
  foreach ($defs['update'] as $n => $desc) {
    if ($n > $installedSchema[$module]) {
      $updates[] = [sprintf('%s_update_%d()', $module, $n), $desc];
    }
  }
  // hook_post_update_NAME: pending when the function name has never been run.
  foreach ($defs['post_update'] as $name => $desc) {
    $fn = sprintf('%s_post_update_%s()', $module, $name);
    if (!in_array(rtrim($fn, '()'), $ranPostUpdates, TRUE)) {
      $postUpdates[] = [$fn, $desc];
    }
  }
  // hook_deploy_NAME: Drush-only, tracked the same way, run after config import.
  foreach ($defs['deploy'] as $name => $desc) {
    $fn = sprintf('%s_deploy_%s()', $module, $name);
    if (!in_array(rtrim($fn, '()'), $ranDeployHooks, TRUE)) {
      $deployHooks[] = [$fn, $desc];
    }
  }
}

$step = function (string $title, array $rows): void {
  echo $title . "\\n";
  if ($rows === []) {
    echo "    (nothing pending)\\n";
    return;
  }
  foreach ($rows as [$fn, $desc]) {
    printf("    %-46s %s\\n", $fn, $desc);
  }
};

echo "drush deploy -- execution plan\\n";
echo str_repeat('=', 29) . "\\n\\n";

$step('1. drush updatedb   [hook_update_N: schema only]', $updates);
echo "\\n";
$step('2. drush updatedb   [hook_post_update_NAME: full container]', $postUpdates);
echo "\\n";
echo "3. drush config:import\\n";
echo "    workflows.workflow.editorial                   Create + all other pending config ops\\n\\n";
$step('4. drush deploy:hook   [hook_deploy_NAME: after config import]', $deployHooks);

echo "\\nSchema versions after step 1:\\n";
foreach ($codebase as $module => $defs) {
  $highest = $defs['update'] === [] ? $installedSchema[$module] : max(array_keys($defs['update']));
  printf("    %-16s %d -> %d\\n", $module, $installedSchema[$module], max($highest, $installedSchema[$module]));
}

echo "\\nSkipped as already applied: " . (count($ranPostUpdates) + count($ranDeployHooks)) . "\\n";
`,
    output: `drush deploy -- execution plan
=============================

1. drush updatedb   [hook_update_N: schema only]
    intranet_core_update_10003()                   Add the uuid column to {intranet_audit}.
    intranet_core_update_10004()                   Backfill uuid values in {intranet_audit}.

2. drush updatedb   [hook_post_update_NAME: full container]
    intranet_core_post_update_resave_landing_pages() Re-save landing pages so the new field populates.

3. drush config:import
    workflows.workflow.editorial                   Create + all other pending config ops

4. drush deploy:hook   [hook_deploy_NAME: after config import]
    intranet_core_deploy_assign_workflow()         Assign the editorial workflow that config:import just created.

Schema versions after step 1:
    intranet_core    10002 -> 10004
    intranet_search  10001 -> 10001

Skipped as already applied: 1
`,
  },

  keyPoints: [
    "Config import only writes config objects. Tables, columns, data backfills and content transforms are update functions, and there is no automatic rollback for either.",
    "hook_update_N lives in MODULE.install, is tracked by an integer in the system.schema key-value collection, runs earliest, and should stay at the schema/raw-SQL level.",
    "hook_post_update_NAME lives in MODULE.post_update.php, is tracked by function name, runs after every module's hook_update_N with a full container — but still before drush config:import.",
    "drush deploy (Drush 13 and later) is: updatedb, config:import, cache:rebuild, deploy:hook, plus cache:warm on Drupal 11.2+. Drush 12 and earlier instead passed --no-cache-clear to updatedb and rebuilt caches before the import too, so old runbooks look different. Either way, anything that needs newly imported config belongs in MODULE.deploy.php as hook_deploy_NAME.",
    "Write every update to be idempotent (guard with tableExists/fieldExists) and free of your own module's classes and constants — it will run years later against code you have since refactored.",
    "Batch long updates with &$sandbox and $sandbox['#finished'], and rehearse drush deploy against a restored production database before it touches prod.",
  ],

  interview: [
    {
      q: "Walk me through your deploy sequence for a Drupal site, and justify the order.",
      a: "New code first — `composer install --no-dev` — then a database dump as the rollback plan, because neither `updatedb` nor `cim` can be undone. Then `drush deploy`, which on Drush 13 and later is `updatedb`, `config:import`, `cache:rebuild`, `deploy:hook` — and against Drupal 11.2+ a final `cache:warm`. Worth knowing that Drush 12 and earlier ran `updatedb --no-cache-clear` and rebuilt caches before the import as well, so an old runbook will not match. Update hooks run before config import because an update may create the schema that incoming config depends on — a new field storage config is meaningless if the table it describes does not exist. The trailing `deploy:hook` step exists precisely because the reverse dependency is also real: some data fixes need config that only exists *after* the import, and `hook_post_update_NAME` fires too early for that. I finish with `drush config:status` in CI and fail the pipeline if it reports any difference, which catches config that drifted on the server.",
    },
    {
      q: "You've written hook_update_N before in Drupal 7. What changed, and when would you reach for hook_post_update_NAME instead?",
      a: "The mechanics of `hook_update_N` are unchanged — numbered functions in `MODULE.install`, compared against a stored schema version, run in numeric order. What changed is that they became the *low-level* slot. Modern Drupal boots enough of the container to run them, but the container may not yet reflect the code you just deployed, so entity and plugin APIs are unsafe there. `hook_post_update_NAME` in `MODULE.post_update.php` runs after every module's `hook_update_N` with a rebuilt container, and is tracked by name rather than number — so you never have to renumber, and two developers can add post-updates on separate branches without a merge conflict over integers. Rule of thumb: schema and raw SQL in `hook_update_N`, anything touching entities, config or services in `hook_post_update_NAME`.",
    },
    {
      q: "An update hook you wrote 14 months ago just fataled on a client site that hadn't deployed since. What went wrong and how do you prevent it?",
      a: "Almost certainly the update called into my own module's code — a service, a class constant, an interface — and that code has since been renamed or had its constructor signature changed. The update is a permanent historical record; the code around it is not. The fix is to treat updates like Doctrine treats migrations: no entities, no repositories, no application classes. Inline the constant's literal value, use `\\Drupal::database()` and the config API directly, and only lean on core services whose ids are stable. The other common cause is non-idempotency — a previous run timed out halfway — so every update should guard with `tableExists()` / `fieldExists()` and use `&$sandbox` batching so it can be re-entered safely.",
    },
    {
      q: "How do you test that a deploy will actually work before you run it on production?",
      a: "Restore a recent production database into a scratch environment — sanitised with `drush sql:sanitize` if it leaves the network — then run the exact deploy script CI will run, not a hand-typed approximation. Dev databases are useless for this: they lack the row volumes that make a batch time out and the messy legacy rows that break a naive `UPDATE`. I time `drush deploy` on that copy to size the maintenance window, then run it a second time on the same database to prove the updates are idempotent and that `drush config:status` reports clean. In CI this becomes a nightly job that restores the latest prod backup and deploys the release branch onto it, so a broken update hook fails a pipeline rather than a launch.",
    },
  ],

  quiz: [
    {
      question:
        "In the sequence run by `drush deploy`, when do hook_post_update_NAME implementations execute?",
      options: [
        "Before any hook_update_N, so they can prepare data for the schema changes",
        "As part of `drush updatedb`, after all hook_update_N but before `drush config:import`",
        "After `drush config:import`, which is why they can rely on newly imported config",
        "Only when you explicitly run `drush deploy:hook`",
      ],
      answerIndex: 1,
      explain:
        "`drush deploy` (Drush 13 and later) runs `updatedb`, `config:import`, `cache:rebuild`, `deploy:hook`, and on Drupal 11.2+ a closing `cache:warm`. Post-updates run inside that first `updatedb` step, after every module's hook_update_N but before config is imported. Logic that depends on newly imported config must go in MODULE.deploy.php as hook_deploy_NAME, which `drush deploy:hook` runs last.",
    },
    {
      question:
        "Why is calling `\\Drupal::service('mymodule.thing')->doWork()` inside hook_update_N a bad idea?",
      options: [
        "The service container is not available at all during update hooks",
        "Update hooks run in a separate PHP process that cannot autoload custom modules",
        "The update is permanent but the service is not — it may be renamed or refactored long before some site finally runs the update",
        "Drupal blocks service access in .install files and throws a ServiceNotFoundException",
      ],
      answerIndex: 2,
      explain:
        "The container is available (that is why the mistake is easy to make), but the update function is a historical record that must still run years later against refactored code. Freeze the behaviour: raw database API, config API, and literal values rather than your own classes and constants. Doctrine gives the identical warning about using entities inside migrations.",
    },
    {
      question:
        "A deploy times out halfway through `intranet_core_update_10003()`, which creates a table. What must be true for the retried deploy to succeed?",
      options: [
        "Nothing — Drupal wraps each update hook in a transaction and rolls it back automatically on all databases",
        "The update must guard its work, e.g. return early if `$schema->tableExists('intranet_audit')`, because the schema version was not advanced",
        "You must manually delete the row from the `post_update` key-value collection first",
        "You must renumber the function to 10004 so Drupal sees it as pending again",
      ],
      answerIndex: 1,
      explain:
        "Drupal only advances the stored schema version after a hook completes, so a failed update is pending again on the next run — and MySQL will not roll back the DDL it already executed. Idempotency guards (`tableExists`, `fieldExists`, `IS NULL` conditions) are what make retries safe. The `post_update` collection tracks post-updates by name, not numbered update hooks.",
    },
    {
      question:
        "Which of these belongs in a hook_update_N rather than a hook_post_update_NAME?",
      options: [
        "Re-saving every node of a content type so a new computed field populates",
        "Adding an index to a custom module's own database table",
        "Updating a view's display options to use a newly available formatter plugin",
        "Assigning a moderation state to existing content using the entity API",
      ],
      answerIndex: 1,
      explain:
        "Adding an index is a pure schema operation expressible through `\\Drupal::database()->schema()` with no entity, plugin or config API involved — exactly what hook_update_N is for. The other three all need a fully rebuilt container and the entity/config APIs, so they belong in hook_post_update_NAME (or MODULE.deploy.php if they depend on config that this deploy is importing).",
    },
  ],
};

export default lesson;
