import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 2,
  slug: "project-setup-composer-drush",
  title: "Project Setup: Composer + Drush vs Symfony Flex",
  part: "Foundations & Mental Model",
  estMinutes: 12,
  summary:
    "How a Drupal site is scaffolded, wired, and driven from the CLI — mapped onto the Symfony skeleton, Flex, and bin/console you already know.",

  concept: `
You bootstrap a Symfony app with \`composer create-project symfony/skeleton\`,
then **Flex** rewrites your config as you add packages, and you drive everything
with \`bin/console\`. Drupal has the same three moving parts — a Composer
template, a project layout, and a CLI — but they behave differently in ways that
trip up every Symfony dev on day one.

### Scaffolding: template project, no Flex

In Symfony, \`symfony/flex\` is a Composer plugin that runs **recipes**: install
\`symfony/mailer\` and Flex drops a \`config/packages/mailer.yaml\` and a
\`.env\` entry for you. **Drupal has nothing like this.** You start from a
*template* repository instead:

\`\`\`bash
composer create-project drupal/recommended-project my-site
\`\`\`

That template pins core and pulls in \`drupal/core-composer-scaffold\`, which
writes boilerplate (\`index.php\`, \`.htaccess\`, default settings) into a
**\`web/\`** docroot. But installing a contrib module never edits your config —
there are no recipes. You \`composer require\` the code, then **enable** it as a
separate step (see Drush below). Config lives in the database and is *exported*
to YAML, not scaffolded into your repo.

### Directory layout

Symfony puts app code in \`src/\`, config in \`config/\`, and the web root in
\`public/\`. Drupal's docroot is \`web/\` and your code goes in **module
folders**, not a flat \`src/\`:

- \`web/\` — the docroot (Symfony's \`public/\`), containing \`index.php\`.
- \`web/core/\` — Drupal core. **Never edit; never commit changes here.**
- \`web/modules/contrib/\` — third-party modules (Composer-managed).
- \`web/modules/custom/\` — *your* modules; each is its own folder with an
  \`.info.yml\`, \`.routing.yml\`, and \`src/\` (PSR-4, autoloaded).
- \`web/themes/\`, \`web/sites/default/\` — themes and the site's settings.
- \`vendor/\` sits **beside** \`web/\`, outside the docroot — same security
  posture as Symfony keeping \`vendor/\` out of \`public/\`.

There is no single \`src/\` — Drupal is inherently modular, so "your code" is
always inside a module directory whose \`src/\` is PSR-4-autoloaded by convention.

### Configuration: settings.php vs .env

Symfony reads \`.env\` (and \`.env.local\`) into environment variables consumed
by \`config/\`. Drupal's equivalent is **\`web/sites/default/settings.php\`** —
a real PHP file that defines \`$databases\`, a \`$settings\` array, and the
hash salt. Per-environment overrides go in an untracked
\`settings.local.php\`, included at the bottom of \`settings.php\` (the analogue
of \`.env.local\`). You *can* pull secrets from \`getenv()\` inside
\`settings.php\`, but the file itself — not a \`.env\` — is the entry point.

### The CLI: Drush vs bin/console

\`bin/console\` ships **inside** your Symfony app. **Drush** is a separate
Composer dependency (\`composer require drush/drush\`) that boots your site and
runs commands against it: \`drush pm:install\`, \`drush cache:rebuild\`,
\`drush config:export\`. It is the tool you will live in.
`,

  comparisons: [
    {
      label: "Scaffolding a new project",
      intro:
        "Both start from a Composer template. The difference is what happens after: Symfony's Flex configures packages via recipes; Drupal only fetches code and scaffolds a docroot — enabling and configuring are separate, later steps.",
      php: `# Symfony: skeleton + Flex
composer create-project symfony/skeleton my-app
cd my-app

# Flex runs a recipe: writes config/packages/mailer.yaml,
# adds MAILER_DSN to .env, registers the bundle for you.
composer require symfony/mailer`,
      ts: `# Drupal: template project, NO recipes
composer create-project drupal/recommended-project my-site
cd my-site

# Fetches code into web/modules/contrib only.
# It writes NO config and does NOT enable the module.
composer require drupal/pathauto drush/drush`,
      note:
        "There is no Flex in Drupal. `composer require` places code; a second, explicit `drush pm:install` step turns it on. Config is exported to YAML, never generated by a recipe.",
      leftLang: "bash",
      rightLang: "bash",
    },
    {
      label: "Directory layout",
      intro:
        "Where the same kinds of things live. Drupal has a web/ docroot and organises your PHP into module folders instead of a single src/ tree.",
      php: `my-app/            # Symfony
├── bin/console
├── config/         # yaml config
│   └── packages/
├── public/         # docroot
│   └── index.php
├── src/            # YOUR code (PSR-4)
├── var/            # cache, logs
├── vendor/
└── .env`,
      ts: `my-site/           # Drupal
├── web/            # docroot ("public/")
│   ├── index.php
│   ├── core/       # Drupal core — never edit
│   ├── modules/
│   │   ├── contrib/  # composer-managed
│   │   └── custom/   # YOUR modules (each has src/)
│   ├── themes/
│   └── sites/default/settings.php
├── vendor/         # outside the docroot
└── config/sync/    # exported YAML config`,
      note:
        "No flat `src/`: your code lives inside `web/modules/custom/<module>/src/`, which Drupal auto-maps to the `Drupal\\<module>` namespace by convention (registered automatically from the module's machine name — no PSR-4 declaration needed).",
      leftLang: "bash",
      rightLang: "bash",
    },
    {
      label: "Environment config",
      intro:
        "Per-environment settings and secrets. Symfony layers .env files into env vars; Drupal uses a PHP settings file with an untracked local include.",
      php: `# .env (committed defaults)
APP_ENV=dev
DATABASE_URL="mysql://app:pass@127.0.0.1:3306/app"

# .env.local (git-ignored overrides)
APP_ENV=prod
DATABASE_URL="mysql://prod:secret@db:3306/live"

# config/ reads these via %env(DATABASE_URL)%`,
      ts: `<?php
// web/sites/default/settings.php
$databases['default']['default'] = [
  'driver'   => 'mysql',
  'database' => 'app',
  'username' => 'app',
  'password' => getenv('DB_PASS') ?: 'pass',
  'host'     => '127.0.0.1',
];
$settings['hash_salt'] = getenv('HASH_SALT');

// git-ignored per-env overrides (the ".env.local")
if (file_exists(__DIR__ . '/settings.local.php')) {
  include __DIR__ . '/settings.local.php';
}`,
      note:
        "`settings.php` is executable PHP, not a key=value file. It can still call `getenv()`, but the file itself is the entry point — there is no automatic .env loading in core.",
      leftLang: "yaml",
      rightLang: "php",
    },
    {
      label: "Driving the app from the CLI",
      intro:
        "The everyday command loop. bin/console ships inside Symfony; Drush is a separate dependency that boots your site. Note Drush uses the modern colon syntax (Drush 12/13 for Drupal 10/11).",
      php: `# Symfony — bin/console ships in the app
php bin/console cache:clear
php bin/console doctrine:migrations:migrate
php bin/console make:controller
php bin/console debug:router`,
      ts: `# Drupal — Drush is a composer dependency
drush pm:install pathauto      # enable a module (alias: drush en)
drush cache:rebuild            # alias: drush cr
drush config:export            # DB config -> config/sync (cex)
drush config:import            # config/sync -> DB (cim)
drush updatedb                 # run pending DB updates (updb)`,
      note:
        "Drush 12/13 renamed `pm-enable` to `pm:install`; the `en` alias still works. Drush boots a full Drupal, so commands run in the site's real container — like `bin/console`, but shipped separately.",
      leftLang: "bash",
      rightLang: "bash",
    },
  ],

  playground: {
    lang: "php",
    intro:
      "Drupal has no Flex recipe engine: `composer require` only fetches code, and enabling a module is a separate, explicit step. This snippet models that two-phase lifecycle — installed-on-disk vs enabled — the way core's module handler tracks it. Predict the output, then reveal.",
    code: `<?php
// Model of Drupal's "fetched vs enabled" lifecycle (no Flex).

// Phase 1: composer require -> code lands on disk. NOT enabled.
$onDisk = ['pathauto', 'token', 'admin_toolbar'];

// Phase 2: drush pm:install <module> flips it on, one at a time.
$enabled = [];

function pmInstall(string $module, array $onDisk, array &$enabled): void {
    if (!in_array($module, $onDisk, true)) {
        echo "SKIP {$module}: not on disk (composer require it first)\\n";
        return;
    }
    if (in_array($module, $enabled, true)) {
        echo "SKIP {$module}: already enabled\\n";
        return;
    }
    $enabled[] = $module;
    echo "ENABLED {$module}\\n";
}

pmInstall('pathauto', $onDisk, $enabled);
pmInstall('pathauto', $onDisk, $enabled);   // idempotent
pmInstall('metatag', $onDisk, $enabled);     // required but never fetched

echo "on disk : " . implode(', ', $onDisk) . "\\n";
echo "enabled : " . implode(', ', $enabled) . "\\n";
echo "inactive: " . implode(', ', array_values(array_diff($onDisk, $enabled))) . "\\n";`,
    output: `ENABLED pathauto
SKIP pathauto: already enabled
SKIP metatag: not on disk (composer require it first)
on disk : pathauto, token, admin_toolbar
enabled : pathauto
inactive: token, admin_toolbar`,
  },

  keyPoints: [
    "Scaffold with `composer create-project drupal/recommended-project`; there is no Flex, so `composer require` only fetches code into `web/modules/contrib` and configures nothing.",
    "Enabling a module is a separate, explicit step: `drush pm:install <module>` (or `drush en`) — installing the package never turns it on.",
    "The docroot is `web/` (Symfony's `public/`); your PHP lives in `web/modules/custom/<module>/src/`, not a single flat `src/`. Never edit `web/core/`.",
    "`web/sites/default/settings.php` is Drupal's `.env`: real PHP defining `$databases`, `$settings`, and the hash salt, with an untracked `settings.local.php` for per-env overrides.",
    "Drush is a separate Composer dependency (`drush/drush`), not shipped in core; it boots the site to run commands — the `bin/console` equivalent.",
    "Config lives in the database and is exported to YAML with `drush config:export` / imported with `drush config:import` — the deploy-time analogue of migrations.",
  ],

  interview: [
    {
      q: "Coming from Symfony Flex, what surprised you about setting up a Drupal project?",
      a: "The absence of recipes. In Symfony, `composer require symfony/mailer` triggers a Flex recipe that writes `config/packages/mailer.yaml` and a `.env` entry, so the package is wired up the moment it's installed. Drupal has no such mechanism: `composer create-project drupal/recommended-project` gives you a template with a `web/` docroot, and `composer require drupal/pathauto` only drops code into `web/modules/contrib`. Turning it on is a deliberate second step — `drush pm:install pathauto` — and its configuration lives in the database, exported to YAML rather than scaffolded. So install and enable are two distinct phases, which is the mental shift.",
    },
    {
      q: "How does Drupal handle environment-specific configuration compared to Symfony's .env files?",
      a: "Symfony layers `.env`, `.env.local`, and friends into environment variables that `config/` reads via `%env()%`. Drupal's entry point is `web/sites/default/settings.php`, which is executable PHP defining the `$databases` array, a `$settings` array, and the `hash_salt`. Per-environment overrides go in a git-ignored `settings.local.php` that `settings.php` conditionally includes at the end — the analogue of `.env.local`. You can absolutely call `getenv()` inside it to pull secrets from the environment, and on platforms like Acquia or Pantheon that's common, but core doesn't auto-load a `.env` file; the PHP settings file is the seam.",
    },
    {
      q: "What is Drush and how does it relate to bin/console?",
      a: "Drush is Drupal's CLI, conceptually the same role as `bin/console`: it boots the full application container and runs commands against the live site. The key difference is packaging — `bin/console` ships inside every Symfony skeleton, whereas Drush is an external Composer dependency you add with `composer require drush/drush`. Everyday commands include `drush pm:install` to enable modules, `drush cache:rebuild` (`cr`), and `drush config:export`/`config:import` for the config workflow. Note that Drush 12 and 13 — the versions used with Drupal 10 and 11 — adopted colon-delimited names, so the old `pm-enable` is now `pm:install`, though short aliases like `en` and `cr` still work.",
    },
  ],

  quiz: [
    {
      question:
        "You run `composer require drupal/pathauto` on a fresh Drupal 11 site. What state is the module in?",
      options: [
        "Installed and enabled — a Flex-style recipe configured it automatically",
        "Code is on disk in web/modules/contrib but the module is not enabled",
        "Nothing happens until you also edit settings.php",
        "It is enabled but its config still needs to be scaffolded",
      ],
      answerIndex: 1,
      explain:
        "Drupal has no Flex/recipes. `composer require` only places the code under `web/modules/contrib`. Enabling is a separate step: `drush pm:install pathauto` (alias `drush en`).",
    },
    {
      question:
        "In a standard Drupal project, where does your custom PHP code for a module live?",
      options: [
        "In a top-level src/ directory, like Symfony",
        "In web/core/modules/custom/",
        "In web/modules/custom/<module>/src/, with PSR-4 autoloaded by convention",
        "Anywhere under vendor/",
      ],
      answerIndex: 2,
      explain:
        "There is no flat `src/`. Each custom module is a folder under `web/modules/custom/` containing its own `src/`, which Drupal auto-maps to the `Drupal\\<module>` namespace by convention — no PSR-4 declaration needed. `web/core/` is Drupal core and must never be edited.",
    },
    {
      question:
        "Which is the closest Drupal equivalent of Symfony's `.env.local` for git-ignored, per-environment overrides?",
      options: [
        "A .env file in the web/ docroot",
        "web/sites/default/settings.local.php, conditionally included by settings.php",
        "config/sync/*.yml files",
        "The $settings array in web/core/",
      ],
      answerIndex: 1,
      explain:
        "`settings.php` conditionally includes an untracked `settings.local.php` at the end, which holds environment-specific overrides — the analogue of `.env.local`. Core does not auto-load a `.env` file.",
    },
  ],
};

export default lesson;
