import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 2,
  slug: "project-setup",
  title: "Project Setup & Tooling",
  part: "Foundations",
  estMinutes: 10,
  summary:
    "create-next-app scaffolds a TypeScript-first project in one command, and in Next 16 both dev and build run Turbopack by default — no flags, no bundler config.",

  concept: `
One command bootstraps a complete, typed, production-buildable app:

\`\`\`bash
npx create-next-app@latest my-app
\`\`\`

It's the \`composer create-project\` of this world — but instead of pulling
a framework skeleton and then wiring a web server, autoloader, and build
step yourself, everything arrives configured.

### The prompts

The CLI first asks for a project name, then offers a shortcut:

\`\`\`
Would you like to use the recommended Next.js defaults?
    Yes, use recommended defaults - TypeScript, ESLint, Tailwind CSS, App Router, AGENTS.md
    No, reuse previous settings
    No, customize settings
\`\`\`

The recommended defaults are exactly what this course assumes. If you pick
**customize** instead, the questions that matter:

- **TypeScript?** — Yes. The whole ecosystem assumes it.
- **Which linter?** — ESLint / Biome / None.
- **React Compiler?** — the optional optimizing compiler; No is a fine default while learning.
- **Tailwind CSS?** — your call; the course examples don't depend on it.
- **Code inside \`src/\`?** — optional; we'll use the default (\`app/\` at the root).
- **App Router? (recommended)** — Yes, always.
- **Customize the import alias (\`@/*\` by default)?** — the default is good.
- **Include \`AGENTS.md\`?** — a guidance file for AI coding agents; harmless either way.

### The generated tree

\`\`\`
my-app/
├── app/
│   ├── layout.tsx      # root layout — the <html>/<body> shell
│   ├── page.tsx        # the / route
│   └── globals.css
├── public/             # static files, served from / (like a docroot)
├── next.config.ts      # typed framework config
├── tsconfig.json
├── next-env.d.ts       # generated — never edit it
└── package.json
\`\`\`

Two files deserve a closer look.

**\`tsconfig.json\`** ships with \`strict: true\`, a \`paths\` alias mapping
\`@/*\` to the project root (so \`import { db } from "@/lib/db"\` works from
any depth — think of it as a PSR-4 prefix for your own code), and a
\`plugins\` entry named \`next\`. That plugin runs inside your editor's
TypeScript language service and teaches it Next.js rules: it validates
route file exports, autocompletes config options, and powers the typed
route helpers you'll meet later.

**\`next-env.d.ts\`** is generated by the framework (regenerated by
\`next dev\`, \`next build\`, or \`next typegen\`). It pulls in Next's type
definitions so TypeScript understands things like image imports. Don't
edit it — your own ambient types belong in a separate \`.d.ts\` file.

### The scripts — and where the bundler went

\`\`\`json
{
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  }
}
\`\`\`

In Next.js 16, **Turbopack is stable and the default** for both \`next dev\`
and \`next build\`. If you see \`"dev": "next dev --turbopack"\` in a
tutorial, that's Next 15 vintage — the flag is no longer needed. Turbopack
options now live at the **top level** of \`next.config.ts\` (they were under
\`experimental.turbopack\` in 15):

\`\`\`ts
// next.config.ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  turbopack: {
    // loader/resolution options when you need them — usually you don't
  },
};

export default nextConfig;
\`\`\`

### The dev loop, compared to \`php -S\`

\`php -S localhost:8000\` gives you a request-time interpreter: edit a file,
refresh the browser, see the change. \`next dev\` gives you the same
edit-and-see loop plus three things PHP's built-in server never had:
**Fast Refresh** (the browser updates in place without a manual reload,
preserving component state where possible), **live type errors** overlaid
in the browser, and on-demand compilation — Turbopack compiles only the
routes you actually visit, so a large app still starts in under a second.
`,

  comparisons: [
    {
      label: "Bootstrapping a project",
      intro:
        "Getting from an empty directory to a running, framework-shaped app. Both are one scaffold command — the difference is what still needs wiring afterwards.",
      php: `# Classic PHP bootstrap
composer create-project laravel/laravel my-app
cd my-app
cp .env.example .env
php artisan key:generate

# then: point a web server (or php artisan serve) at it,
# and set up a frontend build (Vite/Mix) separately
php artisan serve
# Server running on http://127.0.0.1:8000`,
      ts: `# Next.js bootstrap
npx create-next-app@latest my-app
# ✔ Use recommended defaults? Yes — TypeScript, ESLint,
#   Tailwind CSS, App Router, AGENTS.md
cd my-app
npm run dev
#  ▲ Next.js 16.2 (Turbopack)
#  - Local: http://localhost:3000
#  ✓ Ready in 800ms

# frontend, backend, and build tooling: already one app`,
      note: "One scaffold each — but the Next.js project needs no separate web server or frontend build setup, because pages, API routes, and bundling live in the same tool.",
      leftLang: "bash",
      rightLang: "bash",
    },
    {
      label: "Typed framework config",
      intro:
        "Central app configuration. A PHP config file is an array your IDE can't check; next.config.ts is a typed object your editor autocompletes.",
      php: `<?php // config/app.php
return [
    'name' => env('APP_NAME', 'Laravel'),
    'debug' => (bool) env('APP_DEBUG', false),
    'timezone' => 'UTC',
    // a typo'd key here fails silently at runtime,
    // whenever something first reads it
    'timezome' => 'Australia/Sydney',
];`,
      ts: `// next.config.ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Turbopack options live at the TOP level in Next 16
  // (Next 15 had them under experimental.turbopack)
  turbopack: {},
  images: {
    remotePatterns: [{ protocol: "https", hostname: "cdn.example.com" }],
  },
  // typo a key ("imagess") and tsc rejects the file
};

export default nextConfig;`,
      note: "NextConfig is a real type: unknown keys and wrong value shapes are compile errors instead of silently-ignored config, and your editor autocompletes every option.",
      rightLang: "ts",
    },
    {
      label: "Import paths: PSR-4 prefix vs @/* alias",
      intro:
        "Importing your own code from deep inside the tree without ../../../ chains. Composer solves it with an autoload prefix; tsconfig solves it with a path alias.",
      php: `// composer.json maps a namespace prefix to a folder:
// "autoload": { "psr-4": { "App\\\\": "src/" } }

<?php // src/Http/Controllers/PostController.php
namespace App\\Http\\Controllers;

use App\\Repositories\\PostRepository; // resolved via PSR-4

class PostController {
    public function __construct(
        private PostRepository $posts,
    ) {}
}`,
      ts: `// tsconfig.json maps a path prefix to a folder:
// "paths": { "@/*": ["./*"] }

// app/blog/[slug]/page.tsx — three levels deep, no ../../..
import { getPost } from "@/lib/posts";
import { PostCard } from "@/components/PostCard";

export default async function PostPage(props: PageProps<"/blog/[slug]">) {
  const { slug } = await props.params;
  const post = await getPost(slug);
  return <PostCard post={post} />;
}`,
      note: "Same idea as PSR-4 — a stable prefix for your own code — except it's resolved by the bundler and TypeScript rather than a runtime autoloader.",
    },
  ],

  playground: {
    lang: "bash",
    intro:
      "Read the two commands and predict the transcript: which questions create-next-app asks (note the recommended-defaults shortcut), and what next dev reports when it starts. Note what is absent — no --turbopack flag, yet Turbopack runs.",
    code: `npx create-next-app@latest my-app
cd my-app
npm run dev`,
    output: `✔ Would you like to use the recommended Next.js defaults?
  › Yes, use recommended defaults - TypeScript, ESLint, Tailwind CSS, App Router, AGENTS.md
Creating a new Next.js app in /home/you/my-app.

Installing dependencies:
- react
- react-dom
- next

Success! Created my-app at /home/you/my-app

$ npm run dev

> my-app@0.1.0 dev
> next dev

   ▲ Next.js 16.2.0 (Turbopack)
   - Local:        http://localhost:3000
   - Network:      http://192.168.1.20:3000

 ✓ Starting...
 ✓ Ready in 812ms`,
  },

  keyPoints: [
    "`npx create-next-app@latest` is the `composer create-project` of Next.js: one command scaffolds a typed, buildable, runnable app — say Yes to TypeScript and the App Router.",
    "The scripts are just `next dev` / `next build` / `next start` — in Next 16 Turbopack is the stable default for dev AND build, so the `--turbopack` flag you'll see in older tutorials is gone.",
    "Turbopack options live at the top level of `next.config.ts` in 16 (they were `experimental.turbopack` in 15), and `NextConfig` types the whole config file.",
    "`tsconfig.json` ships strict mode, the `@/*` path alias (your PSR-4-style prefix for project imports), and the `next` TS plugin that teaches your editor Next.js's rules.",
    "`next-env.d.ts` is generated by `next dev`/`next build`/`next typegen` — never edit it; put your own ambient types in a separate `.d.ts` file.",
    "`next dev` is `php -S` plus Fast Refresh, in-browser type errors, and on-demand route compilation.",
  ],

  interview: [
    {
      q: "You join a team whose package.json says `next dev --turbopack`. What does that tell you, and would you change it?",
      a: "It tells me the project was set up on Next.js 15, where Turbopack for dev was stable but opt-in via that flag. On Next.js 16, Turbopack is the default bundler for both `next dev` and `next build`, so the flag is redundant — I'd remove it as part of the 16 upgrade. I'd also check `next.config.ts`: Next 15 kept Turbopack options under `experimental.turbopack`, and 16 moves them to a top-level `turbopack` key. It's a small thing, but knowing which flags belong to which major is exactly the kind of signal that separates people who upgraded deliberately from people who copy tutorials.",
    },
    {
      q: "What does the `@/*` path alias do, and where is it configured?",
      a: "It's configured in `tsconfig.json` under `compilerOptions.paths`, mapping `@/*` to the project root (create-next-app sets it up by default and lets you customize it). It means any file can write `import { getPost } from \"@/lib/posts\"` instead of counting `../..` segments, and imports don't break when a file moves deeper in the tree. Coming from PHP, it plays the same role as a PSR-4 prefix in composer.json — a stable namespace root for your own code — except resolution happens at compile/bundle time via TypeScript and Turbopack rather than through a runtime autoloader.",
    },
    {
      q: "What is next-env.d.ts and should it be edited?",
      a: "It's a TypeScript declaration file that Next.js generates and regenerates automatically — `next dev`, `next build`, and `next typegen` all rewrite it. It wires Next's type definitions into the project so TypeScript understands framework-specific things like importing images or CSS modules. It should never be edited, because any change is lost on the next regeneration; project-specific ambient declarations belong in your own separate `.d.ts` file that tsconfig's `include` picks up.",
    },
  ],

  quiz: [
    {
      question:
        "Fresh Next.js 16 project. What's the correct dev script in package.json?",
      options: [
        '"dev": "next dev --turbopack"',
        '"dev": "next dev" — Turbopack is already the default',
        '"dev": "turbopack serve"',
        '"dev": "next dev --webpack" is required for stability',
      ],
      answerIndex: 1,
      explain:
        "In Next 16, Turbopack is stable and the default for both next dev and next build. The --turbopack flag was Next 15's opt-in and is no longer needed.",
    },
    {
      question:
        "Where do Turbopack configuration options live in Next.js 16?",
      options: [
        "In a separate turbopack.config.ts file",
        "Under experimental.turbopack in next.config.ts",
        "At the top level of next.config.ts, as the turbopack key",
        "In package.json under the \"turbopack\" field",
      ],
      answerIndex: 2,
      explain:
        "Next 16 promoted the config from experimental.turbopack (the Next 15 location) to a top-level turbopack key in next.config.ts, matching its stable status.",
    },
    {
      question: "Which statement about next-env.d.ts is true?",
      options: [
        "You should add your custom ambient types to it",
        "It's generated by Next.js (next dev/build/typegen) and must not be edited",
        "It configures environment variables for the dev server",
        "It's only created if you opt out of TypeScript",
      ],
      answerIndex: 1,
      explain:
        "next-env.d.ts pulls Next's type definitions into the project and is regenerated by the framework — edits are overwritten. Despite the name, it has nothing to do with environment variables.",
    },
  ],
};

export default lesson;
