import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 16,
  slug: "generated-types",
  title: "Inside ./$types: Generated Route Types",
  part: "Routing & Data",
  estMinutes: 11,
  summary:
    "What actually lives in a route's ./$types module, where SvelteKit generates it, and why importing from it makes every route refactor-safe.",

  concept: `
Every route folder in a SvelteKit project gets its own virtual module called
\`./$types\`. You never write it — SvelteKit **generates** it by analysing the
files in that folder. Importing from it is the single habit that makes a
SvelteKit codebase feel fully typed with almost no annotation effort.

### What's in the box

For a route like \`src/routes/blog/[slug]/\`, \`./$types\` can export:

- **\`PageLoad\`** / **\`PageServerLoad\`** — the types for the \`load\` function in
  \`+page.ts\` / \`+page.server.ts\`. They already know this route's \`params\`
  (here: \`{ slug: string }\`), so \`params.slug\` is typed and \`params.id\` is a
  compile error.
- **\`LayoutLoad\`** / **\`LayoutServerLoad\`** — the same, for \`+layout.ts\` /
  \`+layout.server.ts\`.
- **\`Actions\`** — the type for the \`actions\` object in \`+page.server.ts\`
  (form actions).
- **\`RequestHandler\`** — the type for \`GET\`/\`POST\`/etc. in \`+server.ts\`
  API endpoints.
- **\`PageData\`** / **\`LayoutData\`** — the *inferred return types* of your load
  functions, merged with parent layout data. This is what the page receives.
- **\`PageProps\`** / **\`LayoutProps\`** (SvelteKit 2.16+) — ready-made prop types
  for the component itself: \`let { data, form }: PageProps = $props();\`.
- **\`RouteParams\`** — just the params object, e.g. \`{ slug: string }\`.
- **\`EntryGenerator\`** — types \`export const entries\` for prerendering dynamic
  routes: it must return an array of valid param objects for *this* route.

### Where they come from

There is no \`$types.d.ts\` file sitting in your route folder. The real files
live under **\`.svelte-kit/types/\`**, one generated \`$types.d.ts\` per route,
regenerated by the dev server as you edit and by \`svelte-kit sync\` (which runs
on \`npm run dev\`, \`build\`, and usually via the \`prepare\` script). Your
\`tsconfig.json\` starts with:

\`\`\`json
{ "extends": "./.svelte-kit/tsconfig.json" }
\`\`\`

The generated tsconfig contains \`rootDirs\` and path mappings that make the
relative import \`./$types\` resolve to the right file in \`.svelte-kit/types\`
for whichever route you're in. That's why a fresh clone shows type errors
until you run \`npm run dev\` or \`svelte-kit sync\` once.

### The one rule

**Always import from \`'./$types'\` — your own route's.** Never import
\`../other-route/$types\`: those types describe *that* route's params and data,
and reaching across breaks the moment either route changes. The payoff of
playing by the rule is that generated types are the **single source of
truth**: change what \`load\` returns, and \`PageData\`, \`PageProps\`, and every
\`data.whatever\` usage in the component re-check instantly. Refactors that
would be a grep-and-pray exercise in PHP become a list of red squiggles.
`,

  comparisons: [
    {
      label: "Typing a load function",
      intro:
        "A blog post route loads the post whose slug is in the URL. Both versions fetch and return the post; only one knows what params contains and what the page will receive.",
      php: `// src/routes/blog/[slug]/+page.ts  (untyped)
export async function load({ params, fetch }) {
  // params is 'any' — params.slgu would pass silently
  const res = await fetch(\`/api/posts/\${params.slug}\`);
  return { post: await res.json() };
}`,
      ts: `// src/routes/blog/[slug]/+page.ts
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ params, fetch }) => {
  // params is typed { slug: string } for THIS route
  const res = await fetch(\`/api/posts/\${params.slug}\`);
  const post: { title: string; body: string } = await res.json();
  return { post };
};`,
      note: "PageLoad already encodes this folder's [slug] param — no hand-written interface, and the return type flows into PageData automatically.",
      leftLang: "js",
      rightLang: "ts",
    },
    {
      label: "Receiving data in the page",
      intro:
        "The +page.svelte next to that load function renders the post. The typed version gets its props type from the same generated module, so data.post is fully known.",
      php: `<!-- src/routes/blog/[slug]/+page.svelte -->
<script>
  let { data } = $props();
  // data is untyped: data.post.tite renders as undefined
</script>

<h1>{data.post.title}</h1>
<article>{data.post.body}</article>`,
      ts: `<!-- src/routes/blog/[slug]/+page.svelte -->
<script lang="ts">
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  // data.post is { title: string; body: string }
</script>

<h1>{data.post.title}</h1>
<article>{data.post.body}</article>`,
      note: "PageProps (2.16+) bundles data (and form, on action pages) into one prop type — rename a field in load and this file errors immediately.",
    },
    {
      label: "Prerender entries for a dynamic route",
      intro:
        "To prerender /blog/[slug] pages at build time, the route exports the list of slugs to render. EntryGenerator ties that list to the route's actual params.",
      php: `// src/routes/blog/[slug]/+page.server.ts  (untyped)
export const prerender = true;

export function entries() {
  // nothing stops a typo'd or missing param key
  return [{ slug: 'hello-world' }, { slyg: 'oops' }];
}`,
      ts: `// src/routes/blog/[slug]/+page.server.ts
import type { EntryGenerator } from './$types';

export const prerender = true;

export const entries: EntryGenerator = () => {
  // must be { slug: string }[] — 'slyg' is a compile error
  return [{ slug: 'hello-world' }, { slug: 'second-post' }];
};`,
      note: "EntryGenerator is generated per-route from the folder name, so the params it demands always match the [brackets] in the path.",
      leftLang: "js",
      rightLang: "ts",
    },
  ],

  playground: {
    lang: "typescript",
    intro:
      "A miniature of what SvelteKit's codegen does for you: infer PageData from the load function itself, so the 'component' below can only read fields that load really returns. Try renaming a returned field and watch the consumer error.",
    code: `// Simulating ./$types: the load function is the single source of truth.

// What SvelteKit knows from the folder name [slug]:
type RouteParams = { slug: string };

// A stand-in for the generated PageLoad type:
type PageLoad = (event: { params: RouteParams }) => Promise<Record<string, unknown>>;

const load = (async ({ params }) => {
  return {
    post: { title: "Hello " + params.slug, words: 42 },
    related: ["intro-to-kit", "runes-101"],
  };
}) satisfies PageLoad;

// The generated PageData is just "whatever load resolves to":
type PageData = Awaited<ReturnType<typeof load>>;

// A stand-in for the component consuming its typed data prop:
function renderPage(data: PageData): string {
  // data.post.title is string, data.related is string[] — all inferred.
  return data.post.title + " (" + data.post.words + " words, " +
    data.related.length + " related)";
}

async function main() {
  const data = await load({ params: { slug: "world" } });
  console.log(renderPage(data));
  // Uncomment to see the source-of-truth effect:
  // console.log(data.post.tite); // error: Property 'tite' does not exist
}

main();`,
  },

  keyPoints: [
    "Every route folder has a generated `./$types` module with `PageLoad`, `PageServerLoad`, `LayoutLoad`, `Actions`, `RequestHandler`, `PageData`, `PageProps`, `RouteParams`, and `EntryGenerator`.",
    "The real files live in `.svelte-kit/types/`, regenerated by the dev server and `svelte-kit sync` — a fresh clone needs one sync before types resolve.",
    "Your `tsconfig.json` extends `./.svelte-kit/tsconfig.json`; its `rootDirs`/paths setup is what makes the `./$types` import resolve.",
    "Always import from your own route's `'./$types'`, never another route's — each module encodes that folder's params and data.",
    "`PageData` is inferred from your `load` return (merged with layout data), so changing `load` re-checks every consumer: generated types are the single source of truth.",
    "`PageProps`/`LayoutProps` (SvelteKit 2.16+) type the component's `$props()` in one line: `let { data }: PageProps = $props();`.",
  ],

  interview: [
    {
      q: "What is `./$types` in SvelteKit and why is it useful?",
      a: "It's a per-route module that SvelteKit generates into `.svelte-kit/types` from your route files and folder names. It exports types like `PageLoad`, `Actions`, `RequestHandler`, and — crucially — `PageData`/`PageProps`, which are *inferred* from what your `load` functions actually return. The value is that you annotate one function with `PageLoad` and everything downstream — params, the data prop in the component, parent data — is typed with zero hand-written interfaces. Change the load function's return shape and the compiler flags every stale consumer, which makes route refactors safe.",
    },
    {
      q: "Why must you import from your own route's `./$types` rather than a shared types file or another route's?",
      a: "Because the generated types are route-specific: `PageLoad` for `blog/[slug]` knows `params` is `{ slug: string }`, and `PageData` there is the merge of that route's load return with its layout chain. Another route's `$types` describes a different params shape and a different data shape, so importing across routes either lies to the compiler or breaks when either route changes. The relative `./$types` import is remapped per-folder by the generated tsconfig, which is exactly what keeps each route honest.",
    },
    {
      q: "A teammate clones the repo and sees hundreds of errors about `./$types` not being found. What's wrong?",
      a: "Nothing is wrong with the code — the generated files just don't exist yet. `$types` modules live in `.svelte-kit/types`, which is gitignored and produced by `svelte-kit sync`. Running `npm run dev` or `npm run build` (or the `prepare` script, which typically calls `svelte-kit sync`) regenerates them and the errors disappear. It's the same idea as a PHP project missing its `vendor/` autoload files until you run `composer install`.",
    },
  ],

  quiz: [
    {
      question: "Where do the `./$types` modules physically live?",
      options: [
        "In each route folder as a hidden `$types.d.ts` file",
        "In `node_modules/@sveltejs/kit/types`",
        "In `.svelte-kit/types/`, generated by the dev server / `svelte-kit sync`",
        "They don't exist anywhere — the TS plugin fakes them in memory",
      ],
      answerIndex: 2,
      explain:
        "SvelteKit writes one `$types.d.ts` per route under `.svelte-kit/types/`, and the generated `.svelte-kit/tsconfig.json` (which your tsconfig extends) maps the relative `./$types` import onto those files.",
    },
    {
      question:
        "Your `load` in `+page.ts` starts returning `{ article }` instead of `{ post }`. What happens to a `+page.svelte` still reading `data.post`?",
      options: [
        "Nothing until runtime — data is only checked in the browser",
        "It becomes a compile error, because PageData is inferred from load's return type",
        "It works: SvelteKit aliases old field names for one release",
        "Only `svelte-check` notices; the editor cannot see generated types",
      ],
      answerIndex: 1,
      explain:
        "`PageData` (and `PageProps`) are derived from the load function's actual return type, so every consumer of the removed field errors immediately — that's the 'single source of truth' payoff.",
    },
    {
      question: "Which type would you use to type-check the `entries` export that lists params to prerender for `blog/[slug]`?",
      options: ["RouteParams", "EntryGenerator", "PageServerLoad", "PageData"],
      answerIndex: 1,
      explain:
        "`EntryGenerator` from `./$types` types `export const entries`, requiring it to return an array of this route's param objects — e.g. `{ slug: string }[]` — so a typo'd key fails to compile.",
    },
  ],
};

export default lesson;
