import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 30,
  slug: "cheatsheet-and-interview",
  title: "Cheatsheet & Interview Prep",
  part: "Patterns & Shipping",
  estMinutes: 14,
  summary:
    "The whole course on one page — every route file's generated type, every rune's typing pattern, the app.d.ts interfaces — plus the interview answers that tie it together.",

  concept: `
Thirty sections compress into three tables. If you can reproduce these from
memory and explain *why* each cell is what it is, you can build — and talk
about — a TypeScript-first SvelteKit app.

### Route files → generated types

Import these from \`./$types\` (regenerated by the sync step as you edit routes):

| File | Type the export | Notes |
| --- | --- | --- |
| \`+page.ts\` | \`export const load: PageLoad\` | universal — runs server *and* client |
| \`+page.server.ts\` | \`PageServerLoad\` + \`export const actions: Actions\` | server-only; secrets & DB live here |
| \`+layout.ts\` | \`LayoutLoad\` | data for the layout and every child |
| \`+layout.server.ts\` | \`LayoutServerLoad\` | server-only layout data |
| \`+server.ts\` | \`export const GET: RequestHandler\` (POST, …) | API endpoints; return \`json(...)\` |
| \`+page.svelte\` | \`let { data }: PageProps = $props()\` | \`PageProps\` since 2.16; \`data\` typed from your loads |
| \`+layout.svelte\` | \`LayoutProps\` | includes typed \`children\` snippet |

The magic: \`data\`'s type is **inferred from what your load functions return**.
Rename a field in \`+page.server.ts\` and every component reading it goes red.

### Runes → typing patterns

| Rune | Pattern | When to annotate |
| --- | --- | --- |
| \`$state\` | \`let count = $state(0)\` | \`$state<Todo[]>([])\` when the initial value doesn't reveal the type (\`[]\`, \`null\`) |
| \`$props\` | \`let { title, done = false }: Props = $props()\` | always — declare an \`interface Props\` |
| \`$derived\` | \`const total = $derived(a + b)\` | rarely — inference from the expression; \`$derived.by(() => ...)\` for multi-line |
| \`$bindable\` | \`let { value = $bindable('') }: Props = $props()\` | the fallback sets the type; parent binds with \`bind:value\` |
| snippets | \`import type { Snippet } from 'svelte'\` → \`row: Snippet<[Item]>\` | tuple generic = the snippet's parameters; render with \`{@render row(item)}\` |

### app.d.ts — the App namespace

| Interface | Types | Set / read |
| --- | --- | --- |
| \`App.Locals\` | \`event.locals\` | set in \`hooks.server.ts\`, read in server loads/actions |
| \`App.PageData\` | common shape of \`page.data\` | what every route's data has in common |
| \`App.Error\` | shape of thrown \`error(...)\` bodies | rendered by \`+error.svelte\` |
| \`App.PageState\` | \`page.state\` for shallow routing | \`pushState\`/\`replaceState\` |
| \`App.Platform\` | adapter-specific context | e.g. Cloudflare bindings |

### The interview frame

When asked about SvelteKit + TypeScript, the strongest thread to pull is:
**the framework generates types from my file structure and my own return
values, so the compiler checks the contracts between server and client that
in PHP I checked with discipline.** Everything else — env modules, zod at the
boundary, typed context — is that same idea applied at each edge of the app.
And the boundary rule in one line: *types are free until the data crosses a
trust boundary; there you validate at runtime and let the validated types flow
inward.*
`,

  comparisons: [
    {
      label: "The whole course in one server route",
      intro:
        "A blog post route with a load function and a comment action — first as it would be written untyped, then with every contract this course covered switched on.",
      php: `// src/routes/blog/[slug]/+page.server.js
import { getPost, addComment } from '$lib/server/db';

export async function load({ params }) {
  const post = await getPost(params.slug);
  if (!post) {
    // is this the right way to 404? who knows
    return { status: 404 };
  }
  return { post };
}

export const actions = {
  comment: async ({ request, locals }) => {
    const data = await request.formData();
    // locals.user? params? all guesswork
    await addComment(locals.user.id, data.get('text'));
    return { ok: true };
  },
};`,
      ts: `// src/routes/blog/[slug]/+page.server.ts
import { error, fail } from '@sveltejs/kit';
import { getPost, addComment } from '$lib/server/db';
import type { PageServerLoad, Actions } from './$types';

export const load: PageServerLoad = async ({ params }) => {
  // params.slug: string — typed from the [slug] directory name
  const post = await getPost(params.slug);
  if (!post) error(404, 'Post not found'); // no throw keyword in Kit 2
  return { post }; // return type flows into PageProps['data']
};

export const actions: Actions = {
  comment: async ({ request, locals }) => {
    if (!locals.user) return fail(401, { message: 'log in first' });

    const text = (await request.formData()).get('text');
    if (typeof text !== 'string' || text.length === 0) {
      return fail(400, { message: 'comment text required' });
    }

    await addComment(locals.user.id, text); // locals typed via app.d.ts
    return { ok: true };
  },
};`,
      note:
        "One file exercises five course themes: generated PageServerLoad/Actions, params typed from the directory name, error() without throw (Kit 2), App.Locals from app.d.ts, and runtime narrowing of FormData.",
      leftLang: "js",
      rightLang: "ts",
    },
    {
      label: "The whole course in one component",
      intro:
        "The page component for that route: typed data from the server, local rune state, and a typed callback prop — the client half of the same contracts.",
      php: `<!-- src/routes/blog/[slug]/+page.svelte -->
<script>
  let { data, form } = $props(); // shapes unknown

  let expanded = $state(false);
</script>

<h1>{data.post.titel}</h1> <!-- typo ships to production -->

{#if form?.message}
  <p class="error">{form.message}</p>
{/if}

<button onclick={() => (expanded = !expanded)}>
  {expanded ? 'Hide' : 'Show'} comments
</button>`,
      ts: `<!-- src/routes/blog/[slug]/+page.svelte -->
<script lang="ts">
  import type { PageProps } from './$types';

  // data: inferred from load's return; form: from the action
  let { data, form }: PageProps = $props();

  let expanded = $state(false);
</script>

<!-- data.post.titel would be a compile error — svelte-check
     sees markup expressions too -->
<h1>{data.post.title}</h1>

{#if form?.message}
  <p class="error">{form.message}</p>
{/if}

<button onclick={() => (expanded = !expanded)}>
  {expanded ? 'Hide' : 'Show'} comments
</button>`,
      note:
        "PageProps (SvelteKit 2.16+) types both data and form from what the server file actually returns — the server/client contract is compiler-checked end to end, markup included.",
    },
  ],

  playground: {
    lang: "typescript",
    intro:
      "A self-marking recap quiz built with course techniques: an interface, a union-typed topic, tuple options and a literal answer index. Three answers are filled in correctly and one is wrong — predict the score line before you run, then fix myAnswers.",
    code: `// The cheatsheet as data — typed the way the course taught.
type Topic = "generated types" | "runes" | "env" | "validation";

interface QuizItem {
  topic: Topic;
  question: string;
  options: [string, string, string];
  answer: 0 | 1 | 2;
}

const quiz: QuizItem[] = [
  {
    topic: "generated types",
    question: "Which type do you give the load export in +page.server.ts?",
    options: ["PageLoad", "PageServerLoad", "RequestHandler"],
    answer: 1,
  },
  {
    topic: "runes",
    question: "How do you type an empty todo list with $state?",
    options: ["let t = $state([])", "let t: any = $state([])", "let t = $state<Todo[]>([])"],
    answer: 2,
  },
  {
    topic: "env",
    question: "Which module is safe to import into a .svelte component?",
    options: ["$env/static/public", "$env/static/private", "$env/dynamic/private"],
    answer: 0,
  },
  {
    topic: "validation",
    question: "What does zod's safeParse return?",
    options: [
      "the data, or it throws",
      "a boolean",
      "a discriminated union: success + data, or failure + error",
    ],
    answer: 2,
  },
];

// Your answers — one is wrong. Find it and fix it.
const myAnswers: number[] = [1, 2, 0, 1];

let score = 0;
quiz.forEach((item, i) => {
  const mine = myAnswers[i];
  const correct = mine === item.answer;
  if (correct) score++;
  console.log((correct ? "PASS" : "FAIL") + " [" + item.topic + "] " + item.question);
  if (!correct) {
    console.log("      correct answer: " + item.options[item.answer]);
  }
});

console.log("Score: " + score + "/" + quiz.length + (score === quiz.length ? " — ready for the interview" : " — one more pass over the cheatsheet"));`,
  },

  keyPoints: [
    "Route file → type: `+page.ts` → `PageLoad`, `+page.server.ts` → `PageServerLoad` + `Actions`, `+server.ts` → `RequestHandler`, and the component gets `PageProps`/`LayoutProps` (2.16+) — all imported from `./$types`.",
    "Rune typing: `$state<T>()` only when the initial value hides the type; `$props()` always destructured against a `Props` interface; `$derived` infers; `$bindable(fallback)` types from its fallback; snippets are `Snippet<[Args]>`.",
    "`app.d.ts` declares the `App` namespace: `Locals` (hooks → server), `PageData`, `Error`, `PageState`, `Platform`.",
    "The generated-types pipeline is the headline: SvelteKit infers `data` from your own load return values, so server/client contract breakage is a compile error, not a production bug.",
    "The boundary rule: types are compile-time only — validate external input at runtime (zod at actions/endpoints), keep secrets in `$env/*/private`, and let validated, inferred types flow inward from there.",
  ],

  interview: [
    {
      q: "How does SvelteKit's TypeScript story differ from React's?",
      a: "React's TypeScript support is bring-your-own contracts: you hand-write the types for route params, loader data and component boundaries, and frameworks on top (Next, Remix) each bolt on their own inference with varying coverage. SvelteKit *generates* types from the project itself: every route directory gets a `./$types` module where `PageServerLoad`, `Actions` and `PageProps` are derived from the file's location — `params.slug` exists because the folder is named `[slug]` — and `data`'s type is inferred from what my load function actually returns. Svelte 5's runes are plain-TypeScript-friendly too: `$state` and `$derived` infer like ordinary variables, without the `useState<T>` generics dance. The net effect is that the server/client contract is compiler-checked with almost no annotation effort.",
    },
    {
      q: "Universal load versus server load — how do you choose?",
      a: "`+page.server.ts` load runs only on the server: it's the place for database access, secrets from `$env/static/private`, and anything reading `locals` — its return value must be serialisable because it crosses the wire. `+page.ts` load is universal: it runs on the server for the first render, then in the browser on client-side navigation, so it must not touch server-only modules — the build enforces that — but it can return non-serialisable values like class instances and is ideal for calling public APIs with the provided `fetch`. They compose: universal load receives the server load's data via `event.data`. My default is server load, moving to universal only when there's a concrete reason.",
    },
    {
      q: "How do you keep server secrets out of the client bundle?",
      a: "Structurally. Secrets live in `$env/static/private` (or `dynamic/private`), and the bundler fails the build if any client-reachable module imports them — same for `$lib/server/` and `.server.ts` files. Only `PUBLIC_`-prefixed variables exist in the public env modules at all. So exposure isn't a code-review concern; it's a compile error. I'd contrast that with PHP, where everything ran server-side and the problem didn't exist — in a full-stack JS framework the same repo compiles into both bundles, so the framework must and does enforce the boundary in the import graph.",
    },
    {
      q: "Runes versus stores — when do you use which?",
      a: "Runes are the default for everything component-shaped in Svelte 5: `$state` and `$derived` cover local state and computed values with plain-variable ergonomics and better TypeScript inference. For state shared beyond a component, I put `$state` in a class or object in a `.svelte.ts` file and share it via typed context — remembering that module-level singletons are shared across requests on the server, so per-user data never goes there. Stores still exist and interoperate (a store's value is reactive in templates via `$store`), and they remain right for custom external subscriptions or interop with libraries that expose them — and `$app/stores` lingers only as the legacy sibling of `$app/state` (2.12+). New code: runes first, stores at the edges.",
    },
  ],

  quiz: [
    {
      question: "Which pairing of route file to generated type is wrong?",
      options: [
        "+page.ts → PageLoad",
        "+page.server.ts → PageServerLoad and Actions",
        "+server.ts → PageProps",
        "+page.svelte → PageProps",
      ],
      answerIndex: 2,
      explain:
        "+server.ts exports HTTP-method handlers typed as RequestHandler. PageProps (since 2.16) belongs to the +page.svelte component, typing its data and form props from the route's load functions and actions.",
    },
    {
      question: "Where does the type of `data` in `+page.svelte` ultimately come from?",
      options: [
        "An interface you write in app.d.ts",
        "It's inferred from the return values of the route's load functions",
        "It's always Record<string, unknown> unless annotated",
        "From a JSON schema in svelte.config.js",
      ],
      answerIndex: 1,
      explain:
        "This is SvelteKit's core TypeScript trick: the sync step generates ./$types by inferring from what your load functions return. Change the return shape and every consuming component re-typechecks — no hand-written contract to maintain.",
    },
    {
      question: "Which statement about `$state` typing is correct?",
      options: [
        "$state always requires an explicit generic",
        "let items = $state([]) gives you string[] automatically",
        "let count = $state(0) infers number; use $state<Todo[]>([]) when the initial value (like []) doesn't reveal the type",
        "$state can only hold primitives",
      ],
      answerIndex: 2,
      explain:
        "$state infers from its initial value like a normal variable declaration. An empty array or null hides the intended type (never[] / null), which is exactly when the explicit generic earns its keep.",
    },
    {
      question: "A junior teammate returns a database client instance from a server load function. What's the problem?",
      options: [
        "Server load can't return objects",
        "Server load data crosses the network to the client, so it must be serialisable — and a DB client would leak server internals anyway",
        "Nothing — SvelteKit proxies the client automatically",
        "It works but disables streaming",
      ],
      answerIndex: 1,
      explain:
        "+page.server.ts data is serialised and sent to the browser: functions and live connections can't make that trip, and secrets must not. Return plain data; keep clients and secrets behind the server boundary ($lib/server, locals, $env/*/private).",
    },
  ],
};

export default lesson;
