import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 28,
  slug: "scaling-architecture",
  title: "Scaling Out: Multiple Web Heads & Shared State",
  part: "Measurement & Operations",
  estMinutes: 13,
  summary:
    "Adding web heads turns every piece of local state — files, cache bins, locks, cron, the database itself — into a distributed-systems problem, and the failures are intermittent rather than loud.",

  concept: `
## Everything that "just worked" was one machine

A single-server Drupal site quietly assumes one disk, one clock, one opcode
cache and one PHP process tree. Put a load balancer in front of three identical
heads and each of those assumptions becomes a coordination problem. Nothing
throws an exception — you get *intermittent* wrongness: the incident headline
updates for two out of three refreshes, an uploaded photo 404s for some
visitors. That is much harder to debug than a crash, so the fix is to go
through the state inventory deliberately.

## The state inventory

**Public files.** Uploads and generated image derivatives land on the disk of
whichever head handled the request. Head 2 does not have them. Either mount one
filesystem at \`\$settings['file_public_path']\` (NFS, AWS EFS, Azure Files) or
move \`public://\` to object storage with a contrib stream wrapper such as
**s3fs** or **flysystem** + **flysystem_s3**. Keep
\`\$settings['file_temp_path']\` local — temp is per-request scratch, sharing it
only adds latency. One non-obvious trap: image-style URLs carry an \`itok\` HMAC
built from the site's private key **and** \`\$settings['hash_salt']\`
(\`ImageStyle::getPathToken()\`). If the salt differs between heads, derivatives
generated by one head are rejected by another.

**Sessions.** Drupal core does not use PHP's file session handler — its session
handler writes to the \`sessions\` table, so a shared database already gives you
shared sessions. That is why a well-built Drupal cluster usually needs no
sticky sessions. Sticky sessions are a crutch for whatever you failed to share;
they also concentrate load and make a head loss user-visible.

**Cache bins.** The default backend is the database — shared. The damage is
usually self-inflicted: someone "optimises" by pointing bins at APCu or a local
file backend, and now \`Cache::invalidateTags()\` only clears the bin of the head
that handled the save. Core already solves the fast-local-plus-consistent case
with \`cache.backend.chainedfast\`, the default for the \`bootstrap\`, \`config\`,
\`discovery\` and \`routes\` bins: APCu in front, a consistent backend behind, with
a last-write timestamp that discards stale local copies. Never bolt a plain
local backend onto \`render\` or \`dynamic_page_cache\`.

**Cron and locks.** Core's cron takes a lock named \`cron\` (900s) before running,
and the default lock backend is \`DatabaseLockBackend\` — shared, so cron will not
double-run across heads *unless* you move locks to a per-head store. What you
should still do is uninstall \`automated_cron\` (or set its interval to 0) and
drive cron from one scheduler, so no visitor ever pays for it. Queue workers are
different: \`DatabaseQueue::claimItem()\` leases items, so parallel runners are
safe, but an expired lease re-delivers — workers must be idempotent.

## Read replicas and lag

\`\$databases['default']['replica'][] = \$info_array;\` declares one or more
replicas; Drupal picks one at random per request. Nothing is routed there
automatically — a query only uses it when code asks for the target, via
\`Database::getConnection('replica')\` or a view with *Use Secondary Server*
ticked. Replication lag then bites: write on the primary, read from the replica
a millisecond later, get the old row. \`Database::ignoreTarget('default',
'replica')\` pins the rest of that request back to the primary.

For a Symfony developer none of this is new — it is the same reasoning behind
sharing a Redis pool, a PDO session handler and a \`PrimaryReadReplicaConnection\`.
Drupal just has more state, and more of it is declared in \`settings.php\`.
`,

  comparisons: [
    {
      label: "Making the cache shared, not per-head",
      intro:
        "Both stacks default to something a single box can hold, and both need an explicit decision to move that state onto a network service every head can reach.",
      php: `# config/packages/cache.yaml — Symfony
framework:
  cache:
    # Every head talks to the same Redis, so a pool written on web1
    # is readable on web2 and web3.
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_DSN)%'
    pools:
      incident.pool:
        adapter: cache.adapter.redis
        default_lifetime: 300
        # TagAwareAdapter — without this, invalidateTags() is a no-op.
        tags: true
  # The lock store is cluster state too. Leave it on the default
  # flock/semaphore store and every head takes its own lock.
  lock: '%env(REDIS_DSN)%'`,
      ts: `<?php
// sites/default/settings.php — Drupal with the contrib redis module.
$settings['redis.connection']['interface'] = 'PhpRedis';
$settings['redis.connection']['host'] = 'redis.internal';
$settings['redis.connection']['port'] = 6379;

// Every bin without an explicit override now lives in Redis.
$settings['cache']['default'] = 'cache.backend.redis';

// This services file also moves the cache-tag checksum, lock and flood
// backends to Redis. The checksum is the important one: tag invalidation
// is only cluster-wide if the checksums are.
$settings['container_yamls'][] = 'modules/contrib/redis/example.services.yml';

// Namespace keys so environments can share one Redis instance.
$settings['cache_prefix'] = 'news_prod_';

// Fine: APCu in front of a consistent backend, with a last-write
// timestamp so a stale local copy is discarded. This is core's default
// for bootstrap/config/discovery/routes.
$settings['cache']['bins']['bootstrap'] = 'cache.backend.chainedfast';

// NEVER: a purely local backend on a bin that holds rendered content.
// $settings['cache']['bins']['render'] = 'cache.backend.apcu';`,
      note: "The failure mode of a per-head bin is not a crash — it is two heads serving correct content and one serving yesterday's headline.",
      leftLang: "yaml",
      rightLang: "php",
    },
    {
      label: "Files that outlive the head that wrote them",
      intro:
        "An upload or a generated image derivative is written to local disk by default. On one server that is invisible; on three it is a 404 for two thirds of your traffic.",
      php: `# config/packages/flysystem.yaml — Symfony
flysystem:
  storages:
    incident.storage:
      adapter: 'aws'
      options:
        client: 'aws_client'
        bucket: 'news-uploads'
        prefix: 'incidents'

# services.yaml — inject the FilesystemOperator, never touch a local path.
services:
  App\\Media\\PhotoUploader:
    arguments:
      $storage: '@incident.storage'

# Thumbnails: LiipImagineBundle writes its cache through a resolver
# (AwsS3Resolver), not to public/media/cache, for exactly this reason.`,
      ts: `<?php
// sites/default/settings.php

// Option A — one POSIX mount every head sees (NFS / EFS / Azure Files).
$settings['file_public_path'] = 'sites/default/files';
$settings['file_private_path'] = '/mnt/shared/private';

// Temp stays LOCAL. It is per-request scratch; sharing it buys you
// nothing and costs a network round trip per chunk.
$settings['file_temp_path'] = '/tmp';

// Option B — object storage via a contrib stream wrapper.
// s3fs can take over public://, or flysystem adds its own scheme:
$settings['flysystem'] = [
  'incidents' => [
    'driver' => 's3',
    'config' => ['bucket' => 'news-uploads', 'region' => 'ap-southeast-2'],
  ],
];

// MUST be byte-identical on every head. Image-style URLs carry an itok
// HMAC keyed on the private key + this salt (ImageStyle::getPathToken()).
// Different salts => derivatives built by web1 are rejected by web2.
$settings['hash_salt'] = file_get_contents('/etc/drupal/salt.txt');`,
      note: "Config sync belongs on the same checklist: $settings['config_sync_directory'] should be deployed with the code so every head sees the same exported config.",
      leftLang: "yaml",
      rightLang: "php",
    },
    {
      label: "Read replicas and the write-then-read trap",
      intro:
        "Both frameworks can send SELECTs to a replica, and both make you opt in — because both know that a replica is a copy that lags.",
      php: `<?php
// config/packages/doctrine.yaml (shown as PHP for the comment density)
//
// doctrine:
//   dbal:
//     connections:
//       default:
//         url: '%env(DATABASE_URL)%'
//         replicas:
//           replica1:
//             url: '%env(DATABASE_REPLICA_URL)%'
//         keep_replica: false
//
// Declaring 'replicas' swaps the wrapper class to
// PrimaryReadReplicaConnection. SELECTs go to a replica until the first
// write, after which the connection sticks to the primary for the rest
// of the request (unless keep_replica is true).

// Force the primary before a read that must see your own write:
$connection = $this->registry->getConnection();
if ($connection instanceof PrimaryReadReplicaConnection) {
    $connection->ensureConnectedToPrimary();
}
$fresh = $repository->find($incidentId);`,
      ts: `<?php
// sites/default/settings.php
$databases['default']['default'] = $primary_info;
$databases['default']['replica'][] = $replica_a_info;
$databases['default']['replica'][] = $replica_b_info;
// Drupal picks ONE replica at random per request. If no 'replica'
// target is declared at all, requests for it silently use 'default'.
// A DECLARED replica that is down throws — there is no failover.

// Nothing is routed to the replica automatically. Opt in per query:
$connection = \\Drupal\\Core\\Database\\Database::getConnection('replica');
$nids = $connection->select('node_field_data', 'n')
  ->fields('n', ['nid'])
  ->condition('n.type', 'incident')
  ->condition('n.status', 1)
  ->range(0, 20)
  ->execute()
  ->fetchCol();

// Views exposes the same choice per view:
//   Advanced > Query settings > "Use Secondary Server"
//   -> \\Drupal\\views\\Plugin\\views\\query\\Sql sets the target to 'replica'.

// After a write, a replica read can return the pre-write row. Pin the
// rest of the request back to the primary:
\\Drupal\\Core\\Database\\Database::ignoreTarget('default', 'replica');`,
      note: "Doctrine sticks to the primary automatically after the first write; Drupal does not — Database::ignoreTarget() is a manual call you have to remember.",
      leftLang: "php",
      rightLang: "php",
    },
    {
      label: "Cron and queues: run them somewhere, not everywhere",
      intro:
        "Scheduled work is the classic multi-head footgun. The answer in both stacks is the same: one scheduler, or a shared lock, plus idempotent workers.",
      php: `# Symfony — option A: schedule on ONE host only (util-1).
#   /etc/systemd/system/incident-rollup.timer
#   [Timer]
#   OnCalendar=*:0/5
#   [Service]
#   ExecStart=/usr/bin/php /srv/app/bin/console app:rollup-incidents

# Option B: let every head try, and make them fight over a shared lock.
composer require symfony/lock
# config/packages/lock.yaml -> framework: { lock: '%env(REDIS_DSN)%' }
php bin/console app:rollup-incidents   # LockableTrait: losers exit quietly

# Messenger consumers are safe on many heads: the transport hands each
# message to exactly one worker, and failures are retried.
php bin/console messenger:consume async --time-limit=3600 --memory-limit=128M`,
      ts: `# Drupal — 1. stop cron firing on visitor requests, on every head.
drush pm:uninstall automated_cron
#   or pin it in settings.php:
#   $config['automated_cron.settings']['interval'] = 0;

# 2. Drive cron from ONE scheduler (a utility host, or a k8s CronJob).
#    */5 * * * * drush --root=/srv/drupal --uri=https://news.example cron
#
#    Core takes a lock named 'cron' (900s) via DatabaseLockBackend, which
#    is shared, so a stray second run is blocked rather than duplicated.
#    That guarantee disappears if you point 'lock' at a per-head store.

# 3. Queues: DatabaseQueue::claimItem() leases each item, so parallel
#    runners will not process the same item concurrently. An expired
#    lease DOES re-deliver, so every QueueWorker must be idempotent.
drush queue:list
drush queue:run incident_notifier --time-limit=55

# 4. Check the shared facts, not one head's log file.
drush state:get system.cron_last
drush core:status`,
      note: "Cron is at-most-once by lock; queues are at-least-once by lease. Design workers for the weaker guarantee.",
      leftLang: "bash",
      rightLang: "bash",
    },
  ],

  playground: {
    intro:
      "Three web heads serve /incident/41. The only difference between the two rounds is whether the cache bin is private to each head or shared — watch what a single tag invalidation reaches.",
    lang: "php",
    code: `<?php
// Three web heads behind a load balancer, serving /incident/41.
// Round 1: every head owns a private cache bin (APCu / local file backend).
// Round 2: every head points at ONE shared bin (Redis).

final class Bin {
  private array $items = [];

  public function get(string $cid): ?string {
    return $this->items[$cid]['value'] ?? NULL;
  }

  public function set(string $cid, string $value, array $tags): void {
    $this->items[$cid] = ['value' => $value, 'tags' => $tags];
  }

  public function invalidateTags(array $tags): int {
    $n = 0;
    foreach ($this->items as $cid => $item) {
      if (array_intersect($tags, $item['tags'])) {
        unset($this->items[$cid]);
        $n++;
      }
    }
    return $n;
  }
}

/** Serve /incident/41 on one head: cache hit, or rebuild from the database. */
function serve(string $head, Bin $bin, string $body): string {
  $cid = 'entity_view:node:41:full';
  $hit = $bin->get($cid);
  if ($hit !== NULL) {
    printf("  %s  HIT   -> %s\\n", $head, $hit);
    return $hit;
  }
  $bin->set($cid, $body, ['node:41', 'node_list']);
  printf("  %s  MISS  -> %s  (rebuilt, cached)\\n", $head, $body);
  return $body;
}

$heads = ['web1', 'web2', 'web3'];
$first = TRUE;

foreach (['private bin per head' => FALSE, 'one shared Redis bin' => TRUE] as $label => $shared) {
  if (!$first) {
    echo "\\n";
  }
  $first = FALSE;
  echo "== $label ==\\n";

  $shared_bin = new Bin();
  $bins = [];
  foreach ($heads as $head) {
    $bins[$head] = $shared ? $shared_bin : new Bin();
  }

  echo " warm-up (headline is 'Ferry delayed'):\\n";
  foreach ($heads as $head) {
    serve($head, $bins[$head], 'Ferry delayed');
  }

  // The editor's save request lands on web2, so core runs
  // Cache::invalidateTags(['node:41']) inside THAT php-fpm process only.
  $cleared = $bins['web2']->invalidateTags(['node:41']);
  echo " editor saves on web2 -> invalidateTags(node:41) cleared $cleared entry\\n";

  echo " next requests (headline is now 'Ferry cancelled'):\\n";
  $stale = 0;
  foreach ($heads as $head) {
    if (serve($head, $bins[$head], 'Ferry cancelled') !== 'Ferry cancelled') {
      $stale++;
    }
  }
  echo " heads serving stale content: $stale of 3\\n";
}

// Same class of bug one layer down: a replica is a second copy that lags.
echo "\\n== write on the primary, read from a replica ==\\n";
$primary = 6;
$replica = $primary;
$primary = 7;
printf(" t=0ms  UPDATE node 41 -> rev %d           target: default\\n", $primary);
printf(" t=5ms  SELECT node 41 -> rev %d  STALE    target: replica (120ms behind)\\n", $replica);
echo "        Database::ignoreTarget('default', 'replica');\\n";
printf(" t=6ms  SELECT node 41 -> rev %d  correct  forced back to default\\n", $primary);
`,
    output: `== private bin per head ==
 warm-up (headline is 'Ferry delayed'):
  web1  MISS  -> Ferry delayed  (rebuilt, cached)
  web2  MISS  -> Ferry delayed  (rebuilt, cached)
  web3  MISS  -> Ferry delayed  (rebuilt, cached)
 editor saves on web2 -> invalidateTags(node:41) cleared 1 entry
 next requests (headline is now 'Ferry cancelled'):
  web1  HIT   -> Ferry delayed
  web2  MISS  -> Ferry cancelled  (rebuilt, cached)
  web3  HIT   -> Ferry delayed
 heads serving stale content: 2 of 3

== one shared Redis bin ==
 warm-up (headline is 'Ferry delayed'):
  web1  MISS  -> Ferry delayed  (rebuilt, cached)
  web2  HIT   -> Ferry delayed
  web3  HIT   -> Ferry delayed
 editor saves on web2 -> invalidateTags(node:41) cleared 1 entry
 next requests (headline is now 'Ferry cancelled'):
  web1  MISS  -> Ferry cancelled  (rebuilt, cached)
  web2  HIT   -> Ferry cancelled
  web3  HIT   -> Ferry cancelled
 heads serving stale content: 0 of 3

== write on the primary, read from a replica ==
 t=0ms  UPDATE node 41 -> rev 7           target: default
 t=5ms  SELECT node 41 -> rev 6  STALE    target: replica (120ms behind)
        Database::ignoreTarget('default', 'replica');
 t=6ms  SELECT node 41 -> rev 7  correct  forced back to default
`,
  },

  keyPoints: [
    "Adding heads converts local state into shared state: public files, cache bins, locks and cron all need an explicit home outside any one server.",
    "Drupal core stores sessions in the database, so a shared DB already gives shared sessions — sticky sessions are a workaround for state you failed to share, not a requirement.",
    "A per-head cache backend silently breaks tag invalidation: Cache::invalidateTags() only clears the bin of the head that handled the write. Use Redis/Memcache, or core's cache.backend.chainedfast where a local layer is worth it.",
    "hash_salt and config_sync_directory must be identical across heads; a mismatched salt breaks image-style itok tokens and every derivative 404s on some heads.",
    "$databases['default']['replica'][] declares replicas, but nothing routes there automatically — code must ask for the 'replica' target, and Database::ignoreTarget() pins a request back to the primary after a write.",
    "Uninstall automated_cron and run cron from one scheduler; queue workers must be idempotent because an expired item lease re-delivers.",
  ],

  interview: [
    {
      q: "We're moving a Drupal site from one server to an autoscaling group. What breaks first, and in what order would you fix it?",
      a: "Files break first and most visibly: uploads and image-style derivatives are written to the local disk of whichever head served the request, so they 404 on the others. I'd move `public://` to a shared mount or object storage (s3fs / flysystem_s3) and confirm `$settings['hash_salt']` is byte-identical everywhere, because image-style URLs carry an `itok` HMAC derived from it. Next I'd audit cache bins — the DB backend is already shared, but any APCu or local-file bin means `Cache::invalidateTags()` reaches only one head, so I'd move to Redis or Memcache with a shared cache-tag checksum service. Then cron: uninstall `automated_cron` and drive `drush cron` from a single scheduler so no visitor pays for it. Sessions I'd check but usually leave alone, since core writes them to the `sessions` table and the database is already shared.",
    },
    {
      q: "Do you need sticky sessions for Drupal behind a load balancer?",
      a: "Normally no. Unlike a stock Symfony app using PHP's file session handler, Drupal core persists sessions to the `sessions` table via its own session handler, so any head with the same database can resume a session. If you do need stickiness, that is a signal that something else is still local — a file-backed cache bin, a local `public://` directory, or a local PHP file storage path — and the better fix is to share that thing. Sticky sessions also hurt you operationally: they concentrate load unevenly and make losing a head user-visible rather than transparent. I'd treat them as a temporary mitigation, not an architecture.",
    },
    {
      q: "How do read replicas work in Drupal, and why can they cause a bug that a single database never would?",
      a: "You declare them in `settings.php` as `$databases['default']['replica'][] = $info_array;` — you can list several and Drupal picks one at random per request; if you never declare a `replica` target, code asking for it just gets `default`. That fallback is about declaration, not health — `Database::getConnection()` only rewrites the target when it is undeclared or has been passed to `ignoreTarget()`. A declared replica that is unreachable throws on connect; nothing retries against the primary, so you still need the replica monitored. Crucially, nothing is routed to a replica automatically: a query only lands there if code calls `Database::getConnection('replica')` or a view has *Use Secondary Server* enabled. The bug is replication lag — you write on the primary and read a millisecond later from a replica that has not applied the change, so the user sees their own edit missing. `Database::ignoreTarget('default', 'replica')` forces the rest of that request back to the primary. Doctrine's `PrimaryReadReplicaConnection` does that stickiness for you after the first write; in Drupal it is a call you have to remember.",
    },
    {
      q: "Two heads both run queue workers. Will items be processed twice?",
      a: "Not concurrently, in the normal case. `DatabaseQueue::claimItem()` claims an item with a conditional UPDATE that sets an `expire` timestamp, and only rows with `expire = 0` are claimable, so exactly one consumer wins the race. But the lease is a timeout, not a guarantee: if a worker crashes or overruns, the item becomes claimable again and is re-delivered. That makes queues at-least-once, so any `QueueWorker` that sends email, charges a card or increments a counter has to be idempotent — check a state flag or use a natural idempotency key. Cron itself is different: core acquires a lock named `cron` through the database-backed lock service before running, so it is effectively at-most-once as long as you have not moved the lock backend to per-head storage.",
    },
  ],

  quiz: [
    {
      question:
        "You point the render cache bin at APCu to speed things up across a three-head cluster. An editor saves a node. What happens?",
      options: [
        "All three heads drop the cached render immediately, because cache tags are stored in the database.",
        "Only the head that handled the save clears its copy; the other two keep serving the old render until it expires.",
        "Nothing changes — APCu bins participate in tag invalidation automatically.",
        "Drupal refuses to boot, because APCu is not a valid cache backend.",
      ],
      answerIndex: 1,
      explain:
        "Cache::invalidateTags() runs inside the PHP process that handled the save, and APCu memory is private to that head's php-fpm pool. The other two heads never see the invalidation. Core's cache.backend.chainedfast solves this properly by pairing APCu with a consistent backend and a last-write timestamp; a bare APCu bin does not.",
    },
    {
      question:
        "Which settings.php line correctly declares a read replica for the default database?",
      options: [
        "$databases['replica']['default'] = $info_array;",
        "$settings['database']['replica'] = $info_array;",
        "$databases['default']['replica'][] = $info_array;",
        "$databases['default']['slave'] = $info_array;",
      ],
      answerIndex: 2,
      explain:
        "The format is $databases[key][target], so the default key with the 'replica' target is $databases['default']['replica'][]. It is an array because you can list several replicas — Drupal chooses one at random per request, and code that asks for a 'replica' target that was never declared transparently gets 'default'.",
    },
    {
      question:
        "After scaling out, image-style derivatives render fine on one head but return 404 on the others, even though the files directory is on a shared NFS mount. What is the most likely cause?",
      options: [
        "The image module has to be reinstalled on every head.",
        "$settings['hash_salt'] differs between heads, so the itok token in the derivative URL fails validation.",
        "NFS cannot store files under sites/default/files.",
        "Image styles are stored in APCu and need a cache rebuild.",
      ],
      answerIndex: 1,
      explain:
        "ImageStyle::getPathToken() builds the itok query parameter as an HMAC over the style ID and URI, keyed on the site's private key plus $settings['hash_salt']. A head with a different salt computes a different token and rejects URLs generated elsewhere. hash_salt must be byte-identical across every head in an environment.",
    },
    {
      question:
        "What is the strongest reason to uninstall the automated_cron module on a multi-head production site?",
      options: [
        "Cron would otherwise run concurrently on all three heads and duplicate every queue item.",
        "automated_cron is deprecated and removed in Drupal 11.",
        "It makes a random visitor's request pay for cron, and cron work belongs on a scheduler you control, not on the request path.",
        "It writes its state to the local filesystem, which is not shared.",
      ],
      answerIndex: 2,
      explain:
        "Core acquires a database-backed lock named 'cron' before running, so concurrent runs are already blocked and queue items are leased rather than duplicated. The real problem is latency and control: automated_cron piggybacks on an end-user request, so an unlucky visitor waits for feed imports and queue processing. Drive cron from one external scheduler instead.",
    },
  ],
};

export default lesson;
