import type { Lesson } from "../../../types";

const lesson: Lesson = {
  id: 26,
  slug: "styling-options",
  title: "Styling React Applications",
  part: "Patterns & Production",
  estMinutes: 11,
  summary:
    "React doesn't ship a styling system — teams pick from plain CSS, CSS Modules, Tailwind, CSS-in-JS, or inline style objects, and knowing the trade-offs is an interview staple.",

  concept: `
React renders elements; it has no opinion about how you style them. That
sounds like a gap, but it's really a menu — and interviewers love asking you
to walk it. The one universal rule: in JSX the attribute is \`className\`, not
\`class\` (\`class\` is a reserved word in JavaScript).

### Plain CSS: one global namespace

The simplest option is exactly what you did in PHP: a global stylesheet,
imported once (\`import './app.css'\` at the entry point — the bundler inlines
it). It works, and for small apps it's fine. The problem is the one you know
from pre-namespace PHP: **every class name lives in one global scope**. Two
components both define \`.title\` and the last stylesheet loaded wins,
silently. BEM naming (\`.card__title--large\`) is the manual discipline teams
invented to fake scoping — the CSS equivalent of prefixing every PHP function
with \`myapp_\` before namespaces existed.

### CSS Modules: scoped classes — the default answer

CSS Modules solve the collision problem the way PHP namespaces did: the tool
makes names local. Name a file \`Card.module.css\` and Vite (out of the box)
treats it as a CSS Module — importing it gives you an **object of generated
class names**:

\`\`\`tsx
import styles from './Card.module.css';

// styles.title is something like "Card_title_x7k2p"
<h2 className={styles.title}>...</h2>
\`\`\`

You write short, honest names (\`.title\`, \`.active\`); the build hashes them
per file, so no two components can collide. It's still just CSS — media
queries, pseudo-classes, no runtime cost. When an interviewer asks "how do
you scope styles to a component?", CSS Modules is the safe default answer.

### Tailwind: utility classes

Tailwind flips the model: instead of naming things, you compose tiny
single-purpose classes directly in the markup —
\`className="flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2"\`.
No stylesheet to name, no collision possible, and the styles live next to
the JSX they affect. It dominates job listings for a reason: in a
component-based world, the *component* is the reusable abstraction, so the
class names stop needing to be. The cost is markup density and a vocabulary
to learn. You don't need to master it for interviews — you need to recognize
it and explain the trade-off.

### CSS-in-JS: recognize it, know why it cooled

Libraries like styled-components and Emotion let you write CSS in template
literals inside your components, with full access to props. They were huge
circa 2018-2021. The ecosystem has since cooled on **runtime** CSS-in-JS:
serializing styles during render costs performance, and the model is
fundamentally at odds with Server Components (styles generated by JS running
in the browser can't be part of server-rendered output without extra
machinery). Teams migrated to CSS Modules, Tailwind, or zero-runtime
compilers. Expect to *read* styled-components in legacy codebases; don't
pick it for new ones.

### Inline style objects: dynamic values only

\`style\` in JSX takes a typed **object**, not a string. Properties are
camelCase (\`backgroundColor\`, not \`background-color\`), and bare numbers
become pixels:

\`\`\`tsx
<div style={{ width: progress + '%', backgroundColor: barColor }} />
\`\`\`

Use it for values that are genuinely computed at runtime — a progress width,
a user-picked color. Don't use it as your styling system: no pseudo-classes,
no media queries, and it defeats CSS caching.

### Conditional classes and the clsx idiom

Every real app toggles classes on state. String concatenation gets ugly
fast, so nearly every React codebase uses \`clsx\` (or the older
\`classnames\`): pass strings, falsy values (skipped), and objects whose keys
are included when the value is truthy:

\`\`\`tsx
<button className={clsx('tab', isActive && 'tab--active', { disabled })}>
\`\`\`

It's a ~200-byte utility, but it appears in so much production code that
implementing it is a common warm-up exercise — which is exactly what the
playground below asks you to do.
`,

  comparisons: [
    {
      label: "Global stylesheet + BEM vs a CSS Module",
      intro:
        "A card component with a scoped title style. The left version relies on naming discipline to avoid collisions; the right one gets scoping from the build tool.",
      php: `<!-- global styles.css + markup: scoping by convention only -->
<style>
  /* BEM: block__element--modifier. Nothing ENFORCES this —
     any other file defining .card__title silently wins or loses. */
  .card { border: 1px solid #ddd; padding: 16px; }
  .card__title { font-size: 1.2rem; }
  .card__title--featured { color: goldenrod; }
</style>

<div class="card">
  <h2 class="card__title card__title--featured">Sale item</h2>
</div>`,
      ts: `/* Card.module.css — names are LOCAL to this file:
   .card  { border: 1px solid #ddd; padding: 16px; }
   .title { font-size: 1.2rem; }
   .featured { color: goldenrod; }                  */

// Card.tsx
import styles from './Card.module.css';

export function Card({ featured }: { featured: boolean }) {
  return (
    <div className={styles.card}>
      {/* renders class="Card_title_x7k2p ..." — collision-proof */}
      <h2 className={featured ? \`\${styles.title} \${styles.featured}\` : styles.title}>
        Sale item
      </h2>
    </div>
  );
}`,
      note:
        "BEM is a naming convention the team must remember; CSS Modules hash class names per file at build time — the same global-namespace fix PHP namespaces gave you, applied to CSS.",
      leftLang: "html",
    },
    {
      label: "Conditional classes: string surgery vs clsx",
      intro:
        "A tab button needs a base class, an active class when selected, and a disabled class when locked. Compare hand-building the string with composing it declaratively.",
      php: `// vanilla JS: manual string assembly
function tabClass(isActive, isLocked) {
  let cls = 'tab';
  if (isActive) {
    cls += ' tab--active';
  }
  if (isLocked) {
    cls += ' tab--disabled';
  }
  return cls;
}

el.className = tabClass(true, false);
// easy to end up with '  ' doubles, trailing
// spaces, or forgotten branches as flags grow`,
      ts: `// Tab.tsx — declarative composition with clsx
import clsx from 'clsx';

function Tab({ isActive, isLocked, label }: TabProps) {
  return (
    <button
      className={clsx(
        'tab',                        // always
        isActive && 'tab--active',    // false is skipped
        { 'tab--disabled': isLocked } // key added when truthy
      )}
      disabled={isLocked}
    >
      {label}
    </button>
  );
}`,
      note:
        "clsx accepts strings, falsy values (discarded), and objects whose truthy-valued keys become classes — the conditional logic reads as data instead of string concatenation.",
      leftLang: "js",
    },
    {
      label: "Dynamic values: echoing a style attribute vs a typed style object",
      intro:
        "A progress bar whose width comes from data. PHP interpolates a style string into markup; React passes a typed object for exactly these runtime-computed cases.",
      php: `<?php // progress.php — string interpolation, no checking
$percent = $tasksDone / $tasksTotal * 100;
$color = $percent > 80 ? '#22c55e' : '#f59e0b';
?>
<div class="bar">
  <!-- typo 'widht' or a missing unit ships silently -->
  <div class="bar-fill"
       style="width: <?= $percent ?>%; background-color: <?= $color ?>">
  </div>
</div>`,
      ts: `// ProgressBar.tsx — style is a typed object, camelCase keys
function ProgressBar({ done, total }: { done: number; total: number }) {
  const percent = (done / total) * 100;
  return (
    <div className="bar">
      <div
        className="bar-fill"
        style={{
          width: \`\${percent}%\`,           // computed at runtime — inline is right here
          backgroundColor: percent > 80 ? '#22c55e' : '#f59e0b',
        }}                                 // 'widht' would be a compile error
      />
    </div>
  );
}`,
      note:
        "Inline style objects are camelCase and type-checked (misspelled properties fail to compile) — but reserve them for genuinely dynamic values; static styling belongs in CSS.",
    },
  ],

  playground: {
    lang: "typescript",
    intro:
      "Implement a miniature clsx: strings pass through, falsy values are discarded, and object keys are included when their value is truthy. Predict the five logged lines, then run it — then try adding array support.",
    code: `// A tiny clsx: the conditional-className idiom used across React codebases.
type ClassValue =
  | string
  | number
  | null
  | undefined
  | false
  | Record<string, boolean | null | undefined>;

function clsx(...args: ClassValue[]): string {
  const classes: string[] = [];
  for (const arg of args) {
    if (!arg) continue; // skips false, null, undefined, '', 0
    if (typeof arg === 'string' || typeof arg === 'number') {
      classes.push(String(arg));
    } else {
      // object form: include each key whose value is truthy
      for (const key of Object.keys(arg)) {
        if (arg[key]) classes.push(key);
      }
    }
  }
  return classes.join(' ');
}

// 1. plain strings
console.log(clsx('btn', 'btn-primary'));

// 2. the && idiom — false branches vanish
const isActive = true;
const isLocked = false;
console.log(clsx('tab', isActive && 'tab--active', isLocked && 'tab--disabled'));

// 3. object form
console.log(clsx('badge', { 'badge--error': true, 'badge--large': false }));

// 4. junk in, clean string out
console.log(clsx(undefined, null, '', 'card', { hidden: false }));

// 5. nothing survives -> empty string
console.log(JSON.stringify(clsx(false, null, { open: false })));`,
  },

  keyPoints: [
    "JSX uses `className` (and a camelCase `style` object) because `class` is a reserved word in JavaScript.",
    "Plain global CSS has the same problem as pre-namespace PHP — one shared namespace; BEM is the manual convention, CSS Modules are the tooling fix.",
    "CSS Modules (`import styles from './X.module.css'`, supported by Vite out of the box) hash class names per file — the default answer for component-scoped CSS.",
    "Tailwind composes utility classes in markup and dominates job listings; the component replaces the class name as the reusable abstraction.",
    "Runtime CSS-in-JS (styled-components, Emotion) has cooled: per-render style serialization costs performance and clashes with Server Components — recognize it in legacy code, don't start new projects with it.",
    "Inline `style` objects are typed and camelCase — use them only for genuinely dynamic values, and reach for `clsx` to compose conditional classes.",
  ],

  interview: [
    {
      q: "What are the main options for styling a React app, and how would you choose?",
      a: "There are roughly five: a plain global stylesheet, CSS Modules, Tailwind, CSS-in-JS, and inline style objects. My default for component-scoped styles is CSS Modules — you write normal CSS, the build tool hashes class names per file, so there's zero runtime cost and no naming collisions. If the team already uses Tailwind I'm happy in it; utilities in markup fit component thinking well and it's the most common choice in job listings. Inline style objects I reserve for genuinely dynamic values like a computed width, since they can't do pseudo-classes or media queries. I'd avoid runtime CSS-in-JS for new work — it costs render-time performance and doesn't fit Server Components — though I can read styled-components code in an existing codebase.",
    },
    {
      q: "Why has the ecosystem moved away from runtime CSS-in-JS libraries like styled-components?",
      a: "Two reasons compounded. First, performance: runtime CSS-in-JS serializes styles while components render and injects them into the document, which adds work to every render — exactly the path you want cheap. Second, architecture: React's direction is Server Components, where component code runs on the server and ships no JS; a styling system that depends on JavaScript executing in the browser at render time fights that model. The community's response was to go back to build-time approaches — CSS Modules, Tailwind, or zero-runtime CSS-in-JS compilers — which produce plain static CSS the server can just send.",
    },
    {
      q: "How do CSS Modules actually work, and what problem do they solve?",
      a: "They solve CSS's global-namespace problem — the same problem PHP had before namespaces, where every function name shared one scope. A file named `Card.module.css` is treated as a module by the bundler (Vite does this out of the box). When I `import styles from './Card.module.css'`, I get an object mapping my authored class names to generated, per-file-unique names — `styles.title` might be `Card_title_x7k2p`. I use those in `className`, so two components can both declare `.title` without ever colliding. It's a compile-time transform: the output is ordinary CSS with ordinary classes, so there's no runtime cost.",
    },
  ],

  quiz: [
    {
      question: "Why does JSX use `className` instead of `class`?",
      options: [
        "className is faster for the browser to parse",
        "`class` is a reserved word in JavaScript, and JSX is JavaScript",
        "React renames it to avoid clashing with CSS Modules",
        "It's purely a style convention with no technical reason",
      ],
      answerIndex: 1,
      explain:
        "JSX compiles to JavaScript, where `class` declares a class. React's DOM prop is therefore `className` (matching the DOM element property of the same name). Similarly, `for` becomes `htmlFor`.",
    },
    {
      question:
        "You import `styles` from `Card.module.css` and use `className={styles.title}`. What does the browser actually receive?",
      options: [
        "class=\"title\" — the import is only for type checking",
        "An inline style attribute generated from the CSS file",
        "A generated, file-scoped class name like \"Card_title_x7k2p\"",
        "A shadow-DOM boundary that isolates the styles",
      ],
      answerIndex: 2,
      explain:
        "CSS Modules are a build-time transform: authored class names are hashed per file and the import gives you the mapping object. The browser gets ordinary CSS and ordinary (unique) class names — no runtime, no shadow DOM.",
    },
    {
      question: "What does `clsx('nav', isOpen && 'nav--open', { pinned: false })` return when `isOpen` is `false`?",
      options: [
        "'nav false'",
        "'nav nav--open'",
        "'nav'",
        "'nav pinned'",
      ],
      answerIndex: 2,
      explain:
        "`isOpen && 'nav--open'` evaluates to `false`, and clsx discards falsy arguments. The object contributes keys only when their values are truthy, so `pinned: false` adds nothing. Only 'nav' survives.",
    },
    {
      question: "When is an inline `style` object the right choice in React?",
      options: [
        "Whenever you want styles scoped to one component",
        "For values computed at runtime, like a progress bar's width",
        "For hover and focus states",
        "Always — it avoids loading CSS files",
      ],
      answerIndex: 1,
      explain:
        "Inline styles shine for genuinely dynamic values that CSS can't know ahead of time. They can't express pseudo-classes or media queries, and using them for static styling bypasses CSS caching — scoping is CSS Modules' job, not inline styles'.",
    },
  ],
};

export default lesson;
